'use strict';(function(){function ba(){Q=!0;for(var a=0;64>a;++a)u[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[a],t["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=a;t[45]=62;t[95]=63}function La(a,b,c){for(var d=[],e=b;e<c;e+=3)b=(a[e]<<16)+(a[e+1]<<8)+a[e+2],d.push(u[b>>18&63]+u[b>>12&63]+u[b>>6&63]+u[b&63]);return d.join("")}function ca(a){Q||ba();for(var b=a.length,c=b%3,d="",e=[],k=0,f=b-c;k<f;k+=16383)e.push(La(a,k,k+16383>f?f:k+16383));
1===c?(a=a[b-1],d+=u[a>>2],d+=u[a<<4&63],d+="=="):2===c&&(a=(a[b-2]<<8)+a[b-1],d+=u[a>>10],d+=u[a>>4&63],d+=u[a<<2&63],d+="=");e.push(d);return e.join("")}function G(a,b,c,d,e){var k=8*e-d-1;var f=(1<<k)-1,h=f>>1,m=-7;e=c?e-1:0;var v=c?-1:1,l=a[b+e];e+=v;c=l&(1<<-m)-1;l>>=-m;for(m+=k;0<m;c=256*c+a[b+e],e+=v,m-=8);k=c&(1<<-m)-1;c>>=-m;for(m+=d;0<m;k=256*k+a[b+e],e+=v,m-=8);if(0===c)c=1-h;else{if(c===f)return k?NaN:Infinity*(l?-1:1);k+=Math.pow(2,d);c-=h}return(l?-1:1)*k*Math.pow(2,c-d)}function H(a,
b,c,d,e,k){var f,h=8*k-e-1,m=(1<<h)-1,v=m>>1,l=23===e?Math.pow(2,-24)-Math.pow(2,-77):0;k=d?0:k-1;var n=d?1:-1,p=0>b||0===b&&0>1/b?1:0;b=Math.abs(b);isNaN(b)||Infinity===b?(b=isNaN(b)?1:0,d=m):(d=Math.floor(Math.log(b)/Math.LN2),1>b*(f=Math.pow(2,-d))&&(d--,f*=2),b=1<=d+v?b+l/f:b+l*Math.pow(2,1-v),2<=b*f&&(d++,f/=2),d+v>=m?(b=0,d=m):1<=d+v?(b=(b*f-1)*Math.pow(2,e),d+=v):(b=b*Math.pow(2,v-1)*Math.pow(2,e),d=0));for(;8<=e;a[c+k]=b&255,k+=n,b/=256,e-=8);d=d<<e|b;for(h+=e;0<h;a[c+k]=d&255,k+=n,d/=256,
h-=8);a[c+k-n]|=128*p}function x(a,b){if((f.TYPED_ARRAY_SUPPORT?2147483647:1073741823)<b)throw new RangeError("Invalid typed array length");f.TYPED_ARRAY_SUPPORT?(a=new Uint8Array(b),a.__proto__=f.prototype):(null===a&&(a=new f(b)),a.length=b);return a}function f(a,b,c){if(!(f.TYPED_ARRAY_SUPPORT||this instanceof f))return new f(a,b,c);if("number"===typeof a){if("string"===typeof b)throw Error("If encoding is specified then the first argument must be a string");return R(this,a)}return da(this,a,b,
c)}function da(a,b,c,d){if("number"===typeof b)throw new TypeError('"value" argument must not be a number');if("undefined"!==typeof ArrayBuffer&&b instanceof ArrayBuffer){b.byteLength;if(0>c||b.byteLength<c)throw new RangeError("'offset' is out of bounds");if(b.byteLength<c+(d||0))throw new RangeError("'length' is out of bounds");b=void 0===c&&void 0===d?new Uint8Array(b):void 0===d?new Uint8Array(b,c):new Uint8Array(b,c,d);f.TYPED_ARRAY_SUPPORT?(a=b,a.__proto__=f.prototype):a=S(a,b);return a}if("string"===
typeof b){d=a;a=c;if("string"!==typeof a||""===a)a="utf8";if(!f.isEncoding(a))throw new TypeError('"encoding" must be a valid string encoding');c=ea(b,a)|0;d=x(d,c);b=d.write(b,a);b!==c&&(d=d.slice(0,b));return d}return Ma(a,b)}function fa(a){if("number"!==typeof a)throw new TypeError('"size" argument must be a number');if(0>a)throw new RangeError('"size" argument must not be negative');}function R(a,b){fa(b);a=x(a,0>b?0:T(b)|0);if(!f.TYPED_ARRAY_SUPPORT)for(var c=0;c<b;++c)a[c]=0;return a}function S(a,
b){var c=0>b.length?0:T(b.length)|0;a=x(a,c);for(var d=0;d<c;d+=1)a[d]=b[d]&255;return a}function Ma(a,b){if(w(b)){var c=T(b.length)|0;a=x(a,c);if(0===a.length)return a;b.copy(a,0,0,c);return a}if(b){if("undefined"!==typeof ArrayBuffer&&b.buffer instanceof ArrayBuffer||"length"in b)return(c="number"!==typeof b.length)||(c=b.length,c=c!==c),c?x(a,0):S(a,b);if("Buffer"===b.type&&ha(b.data))return S(a,b.data)}throw new TypeError("First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.");
}function T(a){if(a>=(f.TYPED_ARRAY_SUPPORT?2147483647:1073741823))throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+(f.TYPED_ARRAY_SUPPORT?2147483647:1073741823).toString(16)+" bytes");return a|0}function w(a){return!(null==a||!a._isBuffer)}function ea(a,b){if(w(a))return a.length;if("undefined"!==typeof ArrayBuffer&&"function"===typeof ArrayBuffer.isView&&(ArrayBuffer.isView(a)||a instanceof ArrayBuffer))return a.byteLength;"string"!==typeof a&&(a=""+a);var c=a.length;
if(0===c)return 0;for(var d=!1;;)switch(b){case "ascii":case "latin1":case "binary":return c;case "utf8":case "utf-8":case void 0:return I(a).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*c;case "hex":return c>>>1;case "base64":return ia(a).length;default:if(d)return I(a).length;b=(""+b).toLowerCase();d=!0}}function Na(a,b,c){var d=!1;if(void 0===b||0>b)b=0;if(b>this.length)return"";if(void 0===c||c>this.length)c=this.length;if(0>=c)return"";c>>>=0;b>>>=0;if(c<=b)return"";
for(a||(a="utf8");;)switch(a){case "hex":a=b;b=c;c=this.length;if(!a||0>a)a=0;if(!b||0>b||b>c)b=c;d="";for(c=a;c<b;++c)a=d,d=this[c],d=16>d?"0"+d.toString(16):d.toString(16),d=a+d;return d;case "utf8":case "utf-8":return ja(this,b,c);case "ascii":a="";for(c=Math.min(this.length,c);b<c;++b)a+=String.fromCharCode(this[b]&127);return a;case "latin1":case "binary":a="";for(c=Math.min(this.length,c);b<c;++b)a+=String.fromCharCode(this[b]);return a;case "base64":return b=0===b&&c===this.length?ca(this):
ca(this.slice(b,c)),b;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":b=this.slice(b,c);c="";for(a=0;a<b.length;a+=2)c+=String.fromCharCode(b[a]+256*b[a+1]);return c;default:if(d)throw new TypeError("Unknown encoding: "+a);a=(a+"").toLowerCase();d=!0}}function y(a,b,c){var d=a[b];a[b]=a[c];a[c]=d}function ka(a,b,c,d,e){if(0===a.length)return-1;"string"===typeof c?(d=c,c=0):2147483647<c?c=2147483647:-2147483648>c&&(c=-2147483648);c=+c;isNaN(c)&&(c=e?0:a.length-1);0>c&&(c=a.length+c);if(c>=
a.length){if(e)return-1;c=a.length-1}else if(0>c)if(e)c=0;else return-1;"string"===typeof b&&(b=f.from(b,d));if(w(b))return 0===b.length?-1:la(a,b,c,d,e);if("number"===typeof b)return b&=255,f.TYPED_ARRAY_SUPPORT&&"function"===typeof Uint8Array.prototype.indexOf?e?Uint8Array.prototype.indexOf.call(a,b,c):Uint8Array.prototype.lastIndexOf.call(a,b,c):la(a,[b],c,d,e);throw new TypeError("val must be string, number or Buffer");}function la(a,b,c,d,e){function f(a,b){return 1===g?a[b]:a.readUInt16BE(b*
g)}var g=1,h=a.length,m=b.length;if(void 0!==d&&(d=String(d).toLowerCase(),"ucs2"===d||"ucs-2"===d||"utf16le"===d||"utf-16le"===d)){if(2>a.length||2>b.length)return-1;g=2;h/=2;m/=2;c/=2}if(e)for(d=-1;c<h;c++)if(f(a,c)===f(b,-1===d?0:c-d)){if(-1===d&&(d=c),c-d+1===m)return d*g}else-1!==d&&(c-=c-d),d=-1;else for(c+m>h&&(c=h-m);0<=c;c--){h=!0;for(d=0;d<m;d++)if(f(a,c+d)!==f(b,d)){h=!1;break}if(h)return c}return-1}function ja(a,b,c){c=Math.min(a.length,c);for(var d=[];b<c;){var e=a[b],f=null,g=239<e?
4:223<e?3:191<e?2:1;if(b+g<=c)switch(g){case 1:128>e&&(f=e);break;case 2:var h=a[b+1];128===(h&192)&&(e=(e&31)<<6|h&63,127<e&&(f=e));break;case 3:h=a[b+1];var m=a[b+2];128===(h&192)&&128===(m&192)&&(e=(e&15)<<12|(h&63)<<6|m&63,2047<e&&(55296>e||57343<e)&&(f=e));break;case 4:h=a[b+1];m=a[b+2];var l=a[b+3];128===(h&192)&&128===(m&192)&&128===(l&192)&&(e=(e&15)<<18|(h&63)<<12|(m&63)<<6|l&63,65535<e&&1114112>e&&(f=e))}null===f?(f=65533,g=1):65535<f&&(f-=65536,d.push(f>>>10&1023|55296),f=56320|f&1023);
d.push(f);b+=g}a=d.length;if(a<=ma)d=String.fromCharCode.apply(String,d);else{c="";for(b=0;b<a;)c+=String.fromCharCode.apply(String,d.slice(b,b+=ma));d=c}return d}function l(a,b,c){if(0!==a%1||0>a)throw new RangeError("offset is not uint");if(a+b>c)throw new RangeError("Trying to access beyond buffer length");}function p(a,b,c,d,e,f){if(!w(a))throw new TypeError('"buffer" argument must be a Buffer instance');if(b>e||b<f)throw new RangeError('"value" argument is out of bounds');if(c+d>a.length)throw new RangeError("Index out of range");
}function J(a,b,c,d){0>b&&(b=65535+b+1);for(var e=0,f=Math.min(a.length-c,2);e<f;++e)a[c+e]=(b&255<<8*(d?e:1-e))>>>8*(d?e:1-e)}function K(a,b,c,d){0>b&&(b=4294967295+b+1);for(var e=0,f=Math.min(a.length-c,4);e<f;++e)a[c+e]=b>>>8*(d?e:3-e)&255}function L(a,b,c,d,e,f){if(c+d>a.length)throw new RangeError("Index out of range");if(0>c)throw new RangeError("Index out of range");}function I(a,b){b=b||Infinity;for(var c,d=a.length,e=null,f=[],g=0;g<d;++g){c=a.charCodeAt(g);if(55295<c&&57344>c){if(!e){if(56319<
c){-1<(b-=3)&&f.push(239,191,189);continue}else if(g+1===d){-1<(b-=3)&&f.push(239,191,189);continue}e=c;continue}if(56320>c){-1<(b-=3)&&f.push(239,191,189);e=c;continue}c=(e-55296<<10|c-56320)+65536}else e&&-1<(b-=3)&&f.push(239,191,189);e=null;if(128>c){if(0>--b)break;f.push(c)}else if(2048>c){if(0>(b-=2))break;f.push(c>>6|192,c&63|128)}else if(65536>c){if(0>(b-=3))break;f.push(c>>12|224,c>>6&63|128,c&63|128)}else if(1114112>c){if(0>(b-=4))break;f.push(c>>18|240,c>>12&63|128,c>>6&63|128,c&63|128)}else throw Error("Invalid code point");
}return f}function na(a){for(var b=[],c=0;c<a.length;++c)b.push(a.charCodeAt(c)&255);return b}function ia(a){a=(a.trim?a.trim():a.replace(/^\s+|\s+$/g,"")).replace(Oa,"");if(2>a.length)a="";else for(;0!==a.length%4;)a+="=";Q||ba();var b=a.length;if(0<b%4)throw Error("Invalid string. Length must be a multiple of 4");var c="="===a[b-2]?2:"="===a[b-1]?1:0;var d=new Pa(3*b/4-c);var e=0<c?b-4:b;var f=0;for(b=0;b<e;b+=4){var g=t[a.charCodeAt(b)]<<18|t[a.charCodeAt(b+1)]<<12|t[a.charCodeAt(b+2)]<<6|t[a.charCodeAt(b+
3)];d[f++]=g>>16&255;d[f++]=g>>8&255;d[f++]=g&255}2===c?(g=t[a.charCodeAt(b)]<<2|t[a.charCodeAt(b+1)]>>4,d[f++]=g&255):1===c&&(g=t[a.charCodeAt(b)]<<10|t[a.charCodeAt(b+1)]<<4|t[a.charCodeAt(b+2)]>>2,d[f++]=g>>8&255,d[f++]=g&255);return d}function C(a,b,c,d){for(var e=0;e<d&&!(e+c>=b.length||e>=a.length);++e)b[e+c]=a[e];return e}function A(a){return null!=a&&(!!a._isBuffer||oa(a)||"function"===typeof a.readFloatLE&&"function"===typeof a.slice&&oa(a.slice(0,0)))}function oa(a){return!!a.constructor&&
"function"===typeof a.constructor.isBuffer&&a.constructor.isBuffer(a)}function z(a,b){var c={seen:[],stylize:Qa};3<=arguments.length&&(c.depth=arguments[2]);4<=arguments.length&&(c.colors=arguments[3]);if("boolean"===typeof b)c.showHidden=b;else if(b&&b&&M(b))for(var d=Object.keys(b),e=d.length;e--;)c[d[e]]=b[d[e]];void 0===c.showHidden&&(c.showHidden=!1);void 0===c.depth&&(c.depth=2);void 0===c.colors&&(c.colors=!1);void 0===c.customInspect&&(c.customInspect=!0);c.colors&&(c.stylize=Ra);return N(c,
a,c.depth)}function Ra(a,b){return(b=z.styles[b])?"\u001b["+z.colors[b][0]+"m"+a+"\u001b["+z.colors[b][1]+"m":a}function Qa(a,b){return a}function Sa(a){var b={};a.forEach(function(a,d){b[a]=!0});return b}function N(a,b,c){if(a.customInspect&&b&&D(b.inspect)&&b.inspect!==z&&(!b.constructor||b.constructor.prototype!==b)){var d=b.inspect(c,a);"string"!==typeof d&&(d=N(a,d,c));return d}if(d=Ta(a,b))return d;var e=Object.keys(b),f=Sa(e);a.showHidden&&(e=Object.getOwnPropertyNames(b));if(O(b)&&(0<=e.indexOf("message")||
0<=e.indexOf("description")))return U(b);if(0===e.length){if(D(b))return a.stylize("[Function"+(b.name?": "+b.name:"")+"]","special");if(E(b))return a.stylize(RegExp.prototype.toString.call(b),"regexp");if(P(b))return a.stylize(Date.prototype.toString.call(b),"date");if(O(b))return U(b)}d="";var g=!1,h=["{","}"];Array.isArray(b)&&(g=!0,h=["[","]"]);D(b)&&(d=" [Function"+(b.name?": "+b.name:"")+"]");E(b)&&(d=" "+RegExp.prototype.toString.call(b));P(b)&&(d=" "+Date.prototype.toUTCString.call(b));O(b)&&
(d=" "+U(b));if(0===e.length&&(!g||0==b.length))return h[0]+d+h[1];if(0>c)return E(b)?a.stylize(RegExp.prototype.toString.call(b),"regexp"):a.stylize("[Object]","special");a.seen.push(b);e=g?Ua(a,b,c,f,e):e.map(function(d){return V(a,b,c,f,d,g)});a.seen.pop();return Va(e,d,h)}function Ta(a,b){if(void 0===b)return a.stylize("undefined","undefined");if("string"===typeof b)return b="'"+JSON.stringify(b).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'",a.stylize(b,"string");if("number"===
typeof b)return a.stylize(""+b,"number");if("boolean"===typeof b)return a.stylize(""+b,"boolean");if(null===b)return a.stylize("null","null")}function U(a){return"["+Error.prototype.toString.call(a)+"]"}function Ua(a,b,c,d,e){for(var f=[],g=0,h=b.length;g<h;++g)Object.prototype.hasOwnProperty.call(b,String(g))?f.push(V(a,b,c,d,String(g),!0)):f.push("");e.forEach(function(e){e.match(/^\d+$/)||f.push(V(a,b,c,d,e,!0))});return f}function V(a,b,c,d,e,f){var g,k;b=Object.getOwnPropertyDescriptor(b,e)||
{value:b[e]};b.get?k=b.set?a.stylize("[Getter/Setter]","special"):a.stylize("[Getter]","special"):b.set&&(k=a.stylize("[Setter]","special"));Object.prototype.hasOwnProperty.call(d,e)||(g="["+e+"]");k||(0>a.seen.indexOf(b.value)?(k=null===c?N(a,b.value,null):N(a,b.value,c-1),-1<k.indexOf("\n")&&(k=f?k.split("\n").map(function(a){return"  "+a}).join("\n").substr(2):"\n"+k.split("\n").map(function(a){return"   "+a}).join("\n"))):k=a.stylize("[Circular]","special"));if(void 0===g){if(f&&e.match(/^\d+$/))return k;
g=JSON.stringify(""+e);g.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(g=g.substr(1,g.length-2),g=a.stylize(g,"name")):(g=g.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),g=a.stylize(g,"string"))}return g+": "+k}function Va(a,b,c){return 60<a.reduce(function(a,b){b.indexOf("\n");return a+b.replace(/\u001b\[\d\d?m/g,"").length+1},0)?c[0]+(""===b?"":b+"\n ")+" "+a.join(",\n  ")+" "+c[1]:c[0]+b+" "+a.join(", ")+" "+c[1]}function E(a){return M(a)&&"[object RegExp]"===Object.prototype.toString.call(a)}
function M(a){return"object"===typeof a&&null!==a}function P(a){return M(a)&&"[object Date]"===Object.prototype.toString.call(a)}function O(a){return M(a)&&("[object Error]"===Object.prototype.toString.call(a)||a instanceof Error)}function D(a){return"function"===typeof a}function pa(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a}function qa(a,b){if(a===b)return 0;for(var c=a.length,d=b.length,e=0,f=Math.min(c,d);e<f;++e)if(a[e]!==
b[e]){c=a[e];d=b[e];break}return c<d?-1:d<c?1:0}function ra(){return"undefined"!==typeof W?W:W=function(){return"foo"===function(){}.name}()}function sa(a){return A(a)||"function"!==typeof X.ArrayBuffer?!1:"function"===typeof ArrayBuffer.isView?ArrayBuffer.isView(a):a?a instanceof DataView||a.buffer&&a.buffer instanceof ArrayBuffer?!0:!1:!1}function n(a,b){a||q(a,!0,b,"==",Y)}function ta(a){if(D(a))return ra()?a.name:(a=a.toString().match(Wa))&&a[1]}function Z(a){this.name="AssertionError";this.actual=
a.actual;this.expected=a.expected;this.operator=a.operator;a.message?(this.message=a.message,this.generatedMessage=!1):(this.message=ua(va(this.actual),128)+" "+this.operator+" "+ua(va(this.expected),128),this.generatedMessage=!0);var b=a.stackStartFunction||q;Error.captureStackTrace?Error.captureStackTrace(this,b):(a=Error(),a.stack&&(a=a.stack,b=ta(b),b=a.indexOf("\n"+b),0<=b&&(b=a.indexOf("\n",b+1),a=a.substring(b+1)),this.stack=a))}function ua(a,b){return"string"===typeof a?a.length<b?a:a.slice(0,
b):a}function va(a){if(ra()||!D(a))return z(a);a=ta(a);return"[Function"+(a?": "+a:"")+"]"}function q(a,b,c,d,e){throw new Z({message:c,actual:a,expected:b,operator:d,stackStartFunction:e});}function Y(a,b){a||q(a,!0,b,"==",Y)}function wa(a,b,c){a!=b&&q(a,b,c,"==",wa)}function xa(a,b,c){a==b&&q(a,b,c,"!=",xa)}function ya(a,b,c){B(a,b,!1)||q(a,b,c,"deepEqual",ya)}function za(a,b,c){B(a,b,!0)||q(a,b,c,"deepStrictEqual",za)}function B(a,b,c,d){if(a===b)return!0;if(A(a)&&A(b))return 0===qa(a,b);if(P(a)&&
P(b))return a.getTime()===b.getTime();if(E(a)&&E(b))return a.source===b.source&&a.global===b.global&&a.multiline===b.multiline&&a.lastIndex===b.lastIndex&&a.ignoreCase===b.ignoreCase;if(null!==a&&"object"===typeof a||null!==b&&"object"===typeof b){if(!sa(a)||!sa(b)||Object.prototype.toString.call(a)!==Object.prototype.toString.call(b)||a instanceof Float32Array||a instanceof Float64Array){if(A(a)!==A(b))return!1;d=d||{actual:[],expected:[]};var e=d.actual.indexOf(a);if(-1!==e&&e===d.expected.indexOf(b))return!0;
d.actual.push(a);d.expected.push(b);return Xa(a,b,c,d)}return 0===qa(new Uint8Array(a.buffer),new Uint8Array(b.buffer))}return c?a===b:a==b}function Aa(a){return"[object Arguments]"==Object.prototype.toString.call(a)}function Xa(a,b,c,d){if(null===a||void 0===a||null===b||void 0===b)return!1;if(pa(a)||pa(b))return a===b;if(c&&Object.getPrototypeOf(a)!==Object.getPrototypeOf(b))return!1;var e=Aa(a),f=Aa(b);if(e&&!f||!e&&f)return!1;if(e)return a=Ba.call(a),b=Ba.call(b),B(a,b,c);e=Ca(a);var g=Ca(b);
if(e.length!==g.length)return!1;e.sort();g.sort();for(f=e.length-1;0<=f;f--)if(e[f]!==g[f])return!1;for(f=e.length-1;0<=f;f--)if(g=e[f],!B(a[g],b[g],c,d))return!1;return!0}function Da(a,b,c){B(a,b,!1)&&q(a,b,c,"notDeepEqual",Da)}function Ea(a,b,c){B(a,b,!0)&&q(a,b,c,"notDeepStrictEqual",Ea)}function Fa(a,b,c){a!==b&&q(a,b,c,"===",Fa)}function Ga(a,b,c){a===b&&q(a,b,c,"!==",Ga)}function Ha(a,b){if(!a||!b)return!1;if("[object RegExp]"==Object.prototype.toString.call(b))return b.test(a);try{if(a instanceof
b)return!0}catch(c){}return Error.isPrototypeOf(b)?!1:!0===b.call({},a)}function Ia(a,b,c,d){if("function"!==typeof b)throw new TypeError('"block" argument must be a function');"string"===typeof c&&(d=c,c=null);try{b()}catch(h){var e=h}b=e;d=(c&&c.name?" ("+c.name+").":".")+(d?" "+d:".");a&&!b&&q(b,c,"Missing expected exception"+d);e="string"===typeof d;var f=!a&&O(b),g=!a&&b&&!c;(f&&e&&Ha(b,c)||g)&&q(b,c,"Got unwanted exception"+d);if(a&&b&&c&&!Ha(b,c)||!a&&b)throw b;}function F(a){if(!(this instanceof
F))return new F(a);if("object"==typeof a&&Array.isArray(a._buffer)&&"number"==typeof a._capacity&&"number"==typeof a._first&&"number"==typeof a._size)for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);else{if("number"!=typeof a||0!=a%1||1>a)throw new TypeError("Invalid capacity");this._buffer=Array(a);this._capacity=a;this._size=this._first=0}}var X="undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{},u=[],t=[],Pa="undefined"!==typeof Uint8Array?
Uint8Array:Array,Q=!1,Ya={}.toString,ha=Array.isArray||function(a){return"[object Array]"==Ya.call(a)};f.TYPED_ARRAY_SUPPORT=void 0!==X.TYPED_ARRAY_SUPPORT?X.TYPED_ARRAY_SUPPORT:!0;f.poolSize=8192;f._augment=function(a){a.__proto__=f.prototype;return a};f.from=function(a,b,c){return da(null,a,b,c)};f.TYPED_ARRAY_SUPPORT&&(f.prototype.__proto__=Uint8Array.prototype,f.__proto__=Uint8Array);f.alloc=function(a,b,c){fa(a);a=0>=a?x(null,a):void 0!==b?"string"===typeof c?x(null,a).fill(b,c):x(null,a).fill(b):
x(null,a);return a};f.allocUnsafe=function(a){return R(null,a)};f.allocUnsafeSlow=function(a){return R(null,a)};f.isBuffer=A;f.compare=function(a,b){if(!w(a)||!w(b))throw new TypeError("Arguments must be Buffers");if(a===b)return 0;for(var c=a.length,d=b.length,e=0,f=Math.min(c,d);e<f;++e)if(a[e]!==b[e]){c=a[e];d=b[e];break}return c<d?-1:d<c?1:0};f.isEncoding=function(a){switch(String(a).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;
default:return!1}};f.concat=function(a,b){if(!ha(a))throw new TypeError('"list" argument must be an Array of Buffers');if(0===a.length)return f.alloc(0);var c;if(void 0===b)for(c=b=0;c<a.length;++c)b+=a[c].length;b=f.allocUnsafe(b);var d=0;for(c=0;c<a.length;++c){var e=a[c];if(!w(e))throw new TypeError('"list" argument must be an Array of Buffers');e.copy(b,d);d+=e.length}return b};f.byteLength=ea;f.prototype._isBuffer=!0;f.prototype.swap16=function(){var a=this.length;if(0!==a%2)throw new RangeError("Buffer size must be a multiple of 16-bits");
for(var b=0;b<a;b+=2)y(this,b,b+1);return this};f.prototype.swap32=function(){var a=this.length;if(0!==a%4)throw new RangeError("Buffer size must be a multiple of 32-bits");for(var b=0;b<a;b+=4)y(this,b,b+3),y(this,b+1,b+2);return this};f.prototype.swap64=function(){var a=this.length;if(0!==a%8)throw new RangeError("Buffer size must be a multiple of 64-bits");for(var b=0;b<a;b+=8)y(this,b,b+7),y(this,b+1,b+6),y(this,b+2,b+5),y(this,b+3,b+4);return this};f.prototype.toString=function(){var a=this.length|
0;return 0===a?"":0===arguments.length?ja(this,0,a):Na.apply(this,arguments)};f.prototype.equals=function(a){if(!w(a))throw new TypeError("Argument must be a Buffer");return this===a?!0:0===f.compare(this,a)};f.prototype.inspect=function(){var a="";0<this.length&&(a=this.toString("hex",0,50).match(/.{2}/g).join(" "),50<this.length&&(a+=" ... "));return"<Buffer "+a+">"};f.prototype.compare=function(a,b,c,d,e){if(!w(a))throw new TypeError("Argument must be a Buffer");void 0===b&&(b=0);void 0===c&&(c=
a?a.length:0);void 0===d&&(d=0);void 0===e&&(e=this.length);if(0>b||c>a.length||0>d||e>this.length)throw new RangeError("out of range index");if(d>=e&&b>=c)return 0;if(d>=e)return-1;if(b>=c)return 1;b>>>=0;c>>>=0;d>>>=0;e>>>=0;if(this===a)return 0;var f=e-d,g=c-b,h=Math.min(f,g);d=this.slice(d,e);a=a.slice(b,c);for(b=0;b<h;++b)if(d[b]!==a[b]){f=d[b];g=a[b];break}return f<g?-1:g<f?1:0};f.prototype.includes=function(a,b,c){return-1!==this.indexOf(a,b,c)};f.prototype.indexOf=function(a,b,c){return ka(this,
a,b,c,!0)};f.prototype.lastIndexOf=function(a,b,c){return ka(this,a,b,c,!1)};f.prototype.write=function(a,b,c,d){if(void 0===b)d="utf8",c=this.length,b=0;else if(void 0===c&&"string"===typeof b)d=b,c=this.length,b=0;else if(isFinite(b))b|=0,isFinite(c)?(c|=0,void 0===d&&(d="utf8")):(d=c,c=void 0);else throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");var e=this.length-b;if(void 0===c||c>e)c=e;if(0<a.length&&(0>c||0>b)||b>this.length)throw new RangeError("Attempt to write outside buffer bounds");
d||(d="utf8");for(e=!1;;)switch(d){case "hex":a:{b=Number(b)||0;d=this.length-b;c?(c=Number(c),c>d&&(c=d)):c=d;d=a.length;if(0!==d%2)throw new TypeError("Invalid hex string");c>d/2&&(c=d/2);for(d=0;d<c;++d){e=parseInt(a.substr(2*d,2),16);if(isNaN(e)){a=d;break a}this[b+d]=e}a=d}return a;case "utf8":case "utf-8":return C(I(a,this.length-b),this,b,c);case "ascii":return C(na(a),this,b,c);case "latin1":case "binary":return C(na(a),this,b,c);case "base64":return C(ia(a),this,b,c);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":d=
a;e=this.length-b;for(var f=[],g=0;g<d.length&&!(0>(e-=2));++g){var h=d.charCodeAt(g);a=h>>8;h%=256;f.push(h);f.push(a)}return C(f,this,b,c);default:if(e)throw new TypeError("Unknown encoding: "+d);d=(""+d).toLowerCase();e=!0}};f.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};var ma=4096;f.prototype.slice=function(a,b){var c=this.length;a=~~a;b=void 0===b?c:~~b;0>a?(a+=c,0>a&&(a=0)):a>c&&(a=c);0>b?(b+=c,0>b&&(b=0)):b>c&&(b=c);b<a&&(b=a);if(f.TYPED_ARRAY_SUPPORT)b=
this.subarray(a,b),b.__proto__=f.prototype;else{c=b-a;b=new f(c,void 0);for(var d=0;d<c;++d)b[d]=this[d+a]}return b};f.prototype.readUIntLE=function(a,b,c){a|=0;b|=0;c||l(a,b,this.length);c=this[a];for(var d=1,e=0;++e<b&&(d*=256);)c+=this[a+e]*d;return c};f.prototype.readUIntBE=function(a,b,c){a|=0;b|=0;c||l(a,b,this.length);c=this[a+--b];for(var d=1;0<b&&(d*=256);)c+=this[a+--b]*d;return c};f.prototype.readUInt8=function(a,b){b||l(a,1,this.length);return this[a]};f.prototype.readUInt16LE=function(a,
b){b||l(a,2,this.length);return this[a]|this[a+1]<<8};f.prototype.readUInt16BE=function(a,b){b||l(a,2,this.length);return this[a]<<8|this[a+1]};f.prototype.readUInt32LE=function(a,b){b||l(a,4,this.length);return(this[a]|this[a+1]<<8|this[a+2]<<16)+16777216*this[a+3]};f.prototype.readUInt32BE=function(a,b){b||l(a,4,this.length);return 16777216*this[a]+(this[a+1]<<16|this[a+2]<<8|this[a+3])};f.prototype.readIntLE=function(a,b,c){a|=0;b|=0;c||l(a,b,this.length);c=this[a];for(var d=1,e=0;++e<b&&(d*=256);)c+=
this[a+e]*d;c>=128*d&&(c-=Math.pow(2,8*b));return c};f.prototype.readIntBE=function(a,b,c){a|=0;b|=0;c||l(a,b,this.length);c=b;for(var d=1,e=this[a+--c];0<c&&(d*=256);)e+=this[a+--c]*d;e>=128*d&&(e-=Math.pow(2,8*b));return e};f.prototype.readInt8=function(a,b){b||l(a,1,this.length);return this[a]&128?-1*(255-this[a]+1):this[a]};f.prototype.readInt16LE=function(a,b){b||l(a,2,this.length);a=this[a]|this[a+1]<<8;return a&32768?a|4294901760:a};f.prototype.readInt16BE=function(a,b){b||l(a,2,this.length);
a=this[a+1]|this[a]<<8;return a&32768?a|4294901760:a};f.prototype.readInt32LE=function(a,b){b||l(a,4,this.length);return this[a]|this[a+1]<<8|this[a+2]<<16|this[a+3]<<24};f.prototype.readInt32BE=function(a,b){b||l(a,4,this.length);return this[a]<<24|this[a+1]<<16|this[a+2]<<8|this[a+3]};f.prototype.readFloatLE=function(a,b){b||l(a,4,this.length);return G(this,a,!0,23,4)};f.prototype.readFloatBE=function(a,b){b||l(a,4,this.length);return G(this,a,!1,23,4)};f.prototype.readDoubleLE=function(a,b){b||
l(a,8,this.length);return G(this,a,!0,52,8)};f.prototype.readDoubleBE=function(a,b){b||l(a,8,this.length);return G(this,a,!1,52,8)};f.prototype.writeUIntLE=function(a,b,c,d){a=+a;b|=0;c|=0;d||p(this,a,b,c,Math.pow(2,8*c)-1,0);d=1;var e=0;for(this[b]=a&255;++e<c&&(d*=256);)this[b+e]=a/d&255;return b+c};f.prototype.writeUIntBE=function(a,b,c,d){a=+a;b|=0;c|=0;d||p(this,a,b,c,Math.pow(2,8*c)-1,0);d=c-1;var e=1;for(this[b+d]=a&255;0<=--d&&(e*=256);)this[b+d]=a/e&255;return b+c};f.prototype.writeUInt8=
function(a,b,c){a=+a;b|=0;c||p(this,a,b,1,255,0);f.TYPED_ARRAY_SUPPORT||(a=Math.floor(a));this[b]=a&255;return b+1};f.prototype.writeUInt16LE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,2,65535,0);f.TYPED_ARRAY_SUPPORT?(this[b]=a&255,this[b+1]=a>>>8):J(this,a,b,!0);return b+2};f.prototype.writeUInt16BE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,2,65535,0);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>8,this[b+1]=a&255):J(this,a,b,!1);return b+2};f.prototype.writeUInt32LE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,4,4294967295,
0);f.TYPED_ARRAY_SUPPORT?(this[b+3]=a>>>24,this[b+2]=a>>>16,this[b+1]=a>>>8,this[b]=a&255):K(this,a,b,!0);return b+4};f.prototype.writeUInt32BE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,4,4294967295,0);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>24,this[b+1]=a>>>16,this[b+2]=a>>>8,this[b+3]=a&255):K(this,a,b,!1);return b+4};f.prototype.writeIntLE=function(a,b,c,d){a=+a;b|=0;d||(d=Math.pow(2,8*c-1),p(this,a,b,c,d-1,-d));d=0;var e=1,f=0;for(this[b]=a&255;++d<c&&(e*=256);)0>a&&0===f&&0!==this[b+d-1]&&(f=1),this[b+
d]=(a/e>>0)-f&255;return b+c};f.prototype.writeIntBE=function(a,b,c,d){a=+a;b|=0;d||(d=Math.pow(2,8*c-1),p(this,a,b,c,d-1,-d));d=c-1;var e=1,f=0;for(this[b+d]=a&255;0<=--d&&(e*=256);)0>a&&0===f&&0!==this[b+d+1]&&(f=1),this[b+d]=(a/e>>0)-f&255;return b+c};f.prototype.writeInt8=function(a,b,c){a=+a;b|=0;c||p(this,a,b,1,127,-128);f.TYPED_ARRAY_SUPPORT||(a=Math.floor(a));0>a&&(a=255+a+1);this[b]=a&255;return b+1};f.prototype.writeInt16LE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,2,32767,-32768);f.TYPED_ARRAY_SUPPORT?
(this[b]=a&255,this[b+1]=a>>>8):J(this,a,b,!0);return b+2};f.prototype.writeInt16BE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,2,32767,-32768);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>8,this[b+1]=a&255):J(this,a,b,!1);return b+2};f.prototype.writeInt32LE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,4,2147483647,-2147483648);f.TYPED_ARRAY_SUPPORT?(this[b]=a&255,this[b+1]=a>>>8,this[b+2]=a>>>16,this[b+3]=a>>>24):K(this,a,b,!0);return b+4};f.prototype.writeInt32BE=function(a,b,c){a=+a;b|=0;c||p(this,a,b,4,2147483647,
-2147483648);0>a&&(a=4294967295+a+1);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>24,this[b+1]=a>>>16,this[b+2]=a>>>8,this[b+3]=a&255):K(this,a,b,!1);return b+4};f.prototype.writeFloatLE=function(a,b,c){c||L(this,a,b,4);H(this,a,b,!0,23,4);return b+4};f.prototype.writeFloatBE=function(a,b,c){c||L(this,a,b,4);H(this,a,b,!1,23,4);return b+4};f.prototype.writeDoubleLE=function(a,b,c){c||L(this,a,b,8);H(this,a,b,!0,52,8);return b+8};f.prototype.writeDoubleBE=function(a,b,c){c||L(this,a,b,8);H(this,a,b,!1,52,8);
return b+8};f.prototype.copy=function(a,b,c,d){c||(c=0);d||0===d||(d=this.length);b>=a.length&&(b=a.length);b||(b=0);0<d&&d<c&&(d=c);if(d===c||0===a.length||0===this.length)return 0;if(0>b)throw new RangeError("targetStart out of bounds");if(0>c||c>=this.length)throw new RangeError("sourceStart out of bounds");if(0>d)throw new RangeError("sourceEnd out of bounds");d>this.length&&(d=this.length);a.length-b<d-c&&(d=a.length-b+c);var e=d-c;if(this===a&&c<b&&b<d)for(d=e-1;0<=d;--d)a[d+b]=this[d+c];else if(1E3>
e||!f.TYPED_ARRAY_SUPPORT)for(d=0;d<e;++d)a[d+b]=this[d+c];else Uint8Array.prototype.set.call(a,this.subarray(c,c+e),b);return e};f.prototype.fill=function(a,b,c,d){if("string"===typeof a){"string"===typeof b?(d=b,b=0,c=this.length):"string"===typeof c&&(d=c,c=this.length);if(1===a.length){var e=a.charCodeAt(0);256>e&&(a=e)}if(void 0!==d&&"string"!==typeof d)throw new TypeError("encoding must be a string");if("string"===typeof d&&!f.isEncoding(d))throw new TypeError("Unknown encoding: "+d);}else"number"===
typeof a&&(a&=255);if(0>b||this.length<b||this.length<c)throw new RangeError("Out of range index");if(c<=b)return this;b>>>=0;c=void 0===c?this.length:c>>>0;a||(a=0);if("number"===typeof a)for(d=b;d<c;++d)this[d]=a;else for(a=w(a)?a:I((new f(a,d)).toString()),e=a.length,d=0;d<c-b;++d)this[d+b]=a[d%e];return this};var Oa=/[^+\/0-9A-Za-z-_]/g,Za="function"===typeof Object.create?function(a,b){a.super_=b;a.prototype=Object.create(b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}})}:
function(a,b){a.super_=b;var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};z.colors={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]};z.styles={special:"cyan",number:"yellow","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"};var $a=Object.prototype.hasOwnProperty,Ca=Object.keys||function(a){var b=
[],c;for(c in a)$a.call(a,c)&&b.push(c);return b},Ba=Array.prototype.slice,W,Wa=/\s*function\s+([^\(\s]*)\s*/;n.AssertionError=Z;Za(Z,Error);n.fail=q;n.ok=Y;n.equal=wa;n.notEqual=xa;n.deepEqual=ya;n.deepStrictEqual=za;n.notDeepEqual=Da;n.notDeepStrictEqual=Ea;n.strictEqual=Fa;n.notStrictEqual=Ga;n.throws=function(a,b,c){Ia(!0,a,b,c)};n.doesNotThrow=function(a,b,c){Ia(!1,a,b,c)};n.ifError=function(a){if(a)throw a;};F.prototype={size:function(){return this._size},capacity:function(){return this._capacity},
enq:function(a){0<this._first?this._first--:this._first=this._capacity-1;this._buffer[this._first]=a;this._size<this._capacity&&this._size++},push:function(a){this._size==this._capacity?(this._buffer[this._first]=a,this._first=(this._first+1)%this._capacity):(this._buffer[(this._first+this._size)%this._capacity]=a,this._size++)},deq:function(){if(0==this._size)throw new RangeError("dequeue on empty buffer");var a=this._buffer[(this._first+this._size-1)%this._capacity];this._size--;return a},pop:function(){return this.deq()},
shift:function(){if(0==this._size)throw new RangeError("shift on empty buffer");var a=this._buffer[this._first];this._first==this._capacity-1?this._first=0:this._first++;this._size--;return a},get:function(a,b){if(0==this._size&&0==a&&(void 0==b||0==b))return[];if("number"!=typeof a||0!=a%1||0>a)throw new TypeError("Invalid start");if(a>=this._size)throw new RangeError("Index past end of buffer: "+a);if(void 0==b)return this._buffer[(this._first+a)%this._capacity];if("number"!=typeof b||0!=b%1||0>
b)throw new TypeError("Invalid end");if(b>=this._size)throw new RangeError("Index past end of buffer: "+b);this._first+a>=this._capacity&&(a-=this._capacity,b-=this._capacity);return this._first+b<this._capacity?this._buffer.slice(this._first+a,this._first+b+1):this._buffer.slice(this._first+a,this._capacity).concat(this._buffer.slice(0,this._first+b+1-this._capacity))},toarray:function(){return 0==this._size?[]:this.get(0,this._size-1)}};let ab=Math.pow(2,32)-1,Ja=a=>a,bb=(a,b=a=>Number(a))=>a.length?
a.reduce((a,d,e)=>{d=b(d);return d>a.x?{x:d,arg:e}:a},{x:-ab,arg:-1}).arg:0,cb=(a,b=Ja)=>Ka(a,b)/a.length,Ka=(a,b=Ja)=>a.reduce((a,d)=>a+b(d),0),db=a=>a.slice().sort((a,c)=>a-c)[Math.round(a.length/2)],eb={power:0,dpower:0},{round:fb,abs:gb,log2:hb,min:ib,max:jb}=Math,kb=fb(sampleRate/128/200);class lb{constructor(){this.window=new Float32Array(128*kb);this.analysis=eb;this.dbMin=-Infinity;this.dbMax=0}analyze(a){if(0===a.length)return this.analysis;if(currentFrame&&0==currentFrame%this.window.length){var b=
this.normalize(this.window.slice());b=this.power(b);this.analysis={power:b,dpower:Math.abs(b-this.analysis.power)}}this.window.set(a,currentFrame%this.window.length);return this.analysis}power(a){return a.reduce((a,c)=>a+c,0)/a.length}normalize(a){for(let b=0;b<a.length;b++){let c=gb(a[b]);c=10*hb(c);c=this.threshold(c);c=Math.pow(2,c/10);a[b]=c}return a}threshold(a){if(this.dbMax===this.dbMin)return a===this.dbMax?0:-Infinity;a=ib(this.dbMax,jb(this.dbMin,a));return(a-this.dbMax)/(a-this.dbMin)}}
class r{constructor(a,b){this.dbMin=a;this.dbMax=b}}r.octave=a=>Math.floor(a/12);r.chroma=a=>a%12;r.f=a=>{n(0<=a&&96>a,`Spectrum.f: expected 0 <= k = ${a} < ${96}`);let b=r.octave(a);a=r.chroma(a);return 16.35*Math.pow(2,b+a/12)};r.hue=a=>{let b=1/12,c=b/8;return b*r.chroma(a)+c*r.octave(a)};r.fmax=16.35*Math.pow(2,96);r.pitch=a=>r.chroma(a)/11;let aa=Math.round(1*sampleRate/128),mb=aa/1*200/60;class nb extends AudioWorkletProcessor{constructor(a){super(a);this.notes=Array(96);this.impulses=new F(aa);
this.onsets=new F(aa);this.onset=a=>{a=Ka(a);var b=this.impulses.toarray();this.impulses.push(a);let d=db(b);b=cb(b);return a>.5*d+.5*b?1:0};for(a=0;96>a;a++)this.notes[a]=new lb}static get parameterDescriptors(){return[{name:"dbMin",maxValue:0},{name:"dbMax",maxValue:0}]}process(a,b,c){a.forEach((a,b)=>{n.equal(a.length,1,`Expected input ${b} to have exactly 1 channel, not ${a.length}`)});let d=a.map(a=>a[0]),e=c.dbMin[0],f=c.dbMax[0];this.notes.forEach((a,b)=>{a.dbMin=e;a.dbMax=f});var g=this.notes.map((a,
b)=>a.analyze(d[b]));a=g.reduce((a,{power:b})=>a+b,0)/96;b=bb(g,a=>a.power);c=r.pitch(b);g=this.onset(g.map(a=>a.dpower));this.onsets.push(g);var h=this.onsets.toarray().reduce((a,b)=>a+b,0);h=Math.min(1,h/mb);this.port.postMessage({hue:r.hue(b),onset:g,pitch:c,power:a,tempo:h});return!0}}registerProcessor("power",nb)})();
//# sourceMappingURL=worklet.js.map
