'use strict';(function(ma){function V(a,b=self){b.addEventListener("message",function e(d){if(d&&d.data){var {id:g,type:h,path:l}=Object.assign({path:[]},d.data),f=(d.data.argumentList||[]).map(x);try{let b=l.slice(0,-1).reduce((a,b)=>a[b],a),e=l.reduce((a,b)=>a[b],a);switch(h){case 0:var m=e;break;case 1:b[l.slice(-1)[0]]=x(d.data.value);m=!0;break;case 2:m=e.apply(b,f);break;case 3:{let a=new e(...f);m=Object.assign(a,{[oa]:!0})}break;case 4:{let {port1:b,port2:d}=new MessageChannel;V(a,d);m=bb(b,
[b])}break;case 5:m=void 0}}catch(na){m=na,W.add(na)}Promise.resolve(m).catch(a=>{W.add(a);return a}).then(a=>{let [d,l]=X(a);b.postMessage(Object.assign(Object.assign({},d),{id:g}),l);5===h&&(b.removeEventListener("message",e),"MessagePort"===b.constructor.name&&b.close())})}});b.start&&b.start()}function K(a){if(a)throw Error("Proxy has been released and is not useable");}function Y(a,b=[],c=function(){}){let d=!1,e=new Proxy(c,{get(c,h){K(d);if(h===cb)return()=>B(a,{type:5,path:b.map(a=>a.toString())}).then(()=>
{"MessagePort"===a.constructor.name&&a.close();d=!0});if("then"===h){if(0===b.length)return{then:()=>e};c=B(a,{type:0,path:b.map(a=>a.toString())}).then(x);return c.then.bind(c)}return Y(a,[...b,h])},set(c,e,l){K(d);const [g,h]=X(l);return B(a,{type:1,path:[...b,e].map(a=>a.toString()),value:g},h).then(x)},apply(c,e,l){K(d);c=b[b.length-1];if(c===db)return B(a,{type:4}).then(x);if("bind"===c)return Y(a,b.slice(0,-1));const [g,h]=pa(l);return B(a,{type:2,path:b.map(a=>a.toString()),argumentList:g},
h).then(x)},construct(c,e){K(d);const [g,h]=pa(e);return B(a,{type:3,path:b.map(a=>a.toString()),argumentList:g},h).then(x)}});return e}function pa(a){a=a.map(X);return[a.map(a=>a[0]),Array.prototype.concat.apply([],a.map(a=>a[1]))]}function bb(a,b){qa.set(a,b);return a}function X(a){for(let [b,c]of ra)if(c.canHandle(a)){let [d,e]=c.serialize(a);return[{type:3,name:b,value:d},e]}return[{type:0,value:a},qa.get(a)||[]]}function x(a){switch(a.type){case 3:return ra.get(a.name).deserialize(a.value);case 0:return a.value}}
function B(a,b,c){return new Promise(d=>{let e=eb();a.addEventListener("message",function l(b){b.data&&b.data.id&&b.data.id===e&&(a.removeEventListener("message",l),d(b.data))});a.start&&a.start();a.postMessage(Object.assign({id:e},b),c)})}function eb(){return Array(4).fill(0).map(()=>Math.floor(Math.random()*Number.MAX_SAFE_INTEGER).toString(16)).join("-")}function sa(){Z=!0;for(var a=0;64>a;++a)u[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[a],t["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=
a;t[45]=62;t[95]=63}function fb(a,b,c){for(var d=[],e=b;e<c;e+=3)b=(a[e]<<16)+(a[e+1]<<8)+a[e+2],d.push(u[b>>18&63]+u[b>>12&63]+u[b>>6&63]+u[b&63]);return d.join("")}function ta(a){Z||sa();for(var b=a.length,c=b%3,d="",e=[],g=0,h=b-c;g<h;g+=16383)e.push(fb(a,g,g+16383>h?h:g+16383));1===c?(a=a[b-1],d+=u[a>>2],d+=u[a<<4&63],d+="=="):2===c&&(a=(a[b-2]<<8)+a[b-1],d+=u[a>>10],d+=u[a>>4&63],d+=u[a<<2&63],d+="=");e.push(d);return e.join("")}function L(a,b,c,d,e){var g=8*e-d-1;var h=(1<<g)-1,l=h>>1,f=-7;
e=c?e-1:0;var m=c?-1:1,k=a[b+e];e+=m;c=k&(1<<-f)-1;k>>=-f;for(f+=g;0<f;c=256*c+a[b+e],e+=m,f-=8);g=c&(1<<-f)-1;c>>=-f;for(f+=d;0<f;g=256*g+a[b+e],e+=m,f-=8);if(0===c)c=1-l;else{if(c===h)return g?NaN:Infinity*(k?-1:1);g+=Math.pow(2,d);c-=l}return(k?-1:1)*g*Math.pow(2,c-d)}function M(a,b,c,d,e,g){var h,f=8*g-e-1,p=(1<<f)-1,m=p>>1,k=23===e?Math.pow(2,-24)-Math.pow(2,-77):0;g=d?0:g-1;var n=d?1:-1,ab=0>b||0===b&&0>1/b?1:0;b=Math.abs(b);isNaN(b)||Infinity===b?(b=isNaN(b)?1:0,d=p):(d=Math.floor(Math.log(b)/
Math.LN2),1>b*(h=Math.pow(2,-d))&&(d--,h*=2),b=1<=d+m?b+k/h:b+k*Math.pow(2,1-m),2<=b*h&&(d++,h/=2),d+m>=p?(b=0,d=p):1<=d+m?(b=(b*h-1)*Math.pow(2,e),d+=m):(b=b*Math.pow(2,m-1)*Math.pow(2,e),d=0));for(;8<=e;a[c+g]=b&255,g+=n,b/=256,e-=8);d=d<<e|b;for(f+=e;0<f;a[c+g]=d&255,g+=n,d/=256,f-=8);a[c+g-n]|=128*ab}function w(a,b){if((f.TYPED_ARRAY_SUPPORT?2147483647:1073741823)<b)throw new RangeError("Invalid typed array length");f.TYPED_ARRAY_SUPPORT?(a=new Uint8Array(b),a.__proto__=f.prototype):(null===a&&
(a=new f(b)),a.length=b);return a}function f(a,b,c){if(!(f.TYPED_ARRAY_SUPPORT||this instanceof f))return new f(a,b,c);if("number"===typeof a){if("string"===typeof b)throw Error("If encoding is specified then the first argument must be a string");return aa(this,a)}return ua(this,a,b,c)}function ua(a,b,c,d){if("number"===typeof b)throw new TypeError('"value" argument must not be a number');if("undefined"!==typeof ArrayBuffer&&b instanceof ArrayBuffer){b.byteLength;if(0>c||b.byteLength<c)throw new RangeError("'offset' is out of bounds");
if(b.byteLength<c+(d||0))throw new RangeError("'length' is out of bounds");b=void 0===c&&void 0===d?new Uint8Array(b):void 0===d?new Uint8Array(b,c):new Uint8Array(b,c,d);f.TYPED_ARRAY_SUPPORT?(a=b,a.__proto__=f.prototype):a=ba(a,b);return a}if("string"===typeof b){d=a;a=c;if("string"!==typeof a||""===a)a="utf8";if(!f.isEncoding(a))throw new TypeError('"encoding" must be a valid string encoding');c=va(b,a)|0;d=w(d,c);b=d.write(b,a);b!==c&&(d=d.slice(0,b));return d}return gb(a,b)}function wa(a){if("number"!==
typeof a)throw new TypeError('"size" argument must be a number');if(0>a)throw new RangeError('"size" argument must not be negative');}function aa(a,b){wa(b);a=w(a,0>b?0:ca(b)|0);if(!f.TYPED_ARRAY_SUPPORT)for(var c=0;c<b;++c)a[c]=0;return a}function ba(a,b){var c=0>b.length?0:ca(b.length)|0;a=w(a,c);for(var d=0;d<c;d+=1)a[d]=b[d]&255;return a}function gb(a,b){if(v(b)){var c=ca(b.length)|0;a=w(a,c);if(0===a.length)return a;b.copy(a,0,0,c);return a}if(b){if("undefined"!==typeof ArrayBuffer&&b.buffer instanceof
ArrayBuffer||"length"in b)return(c="number"!==typeof b.length)||(c=b.length,c=c!==c),c?w(a,0):ba(a,b);if("Buffer"===b.type&&xa(b.data))return ba(a,b.data)}throw new TypeError("First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.");}function ca(a){if(a>=(f.TYPED_ARRAY_SUPPORT?2147483647:1073741823))throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+(f.TYPED_ARRAY_SUPPORT?2147483647:1073741823).toString(16)+" bytes");return a|0}function v(a){return!(null==
a||!a._isBuffer)}function va(a,b){if(v(a))return a.length;if("undefined"!==typeof ArrayBuffer&&"function"===typeof ArrayBuffer.isView&&(ArrayBuffer.isView(a)||a instanceof ArrayBuffer))return a.byteLength;"string"!==typeof a&&(a=""+a);var c=a.length;if(0===c)return 0;for(var d=!1;;)switch(b){case "ascii":case "latin1":case "binary":return c;case "utf8":case "utf-8":case void 0:return N(a).length;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return 2*c;case "hex":return c>>>1;case "base64":return ya(a).length;
default:if(d)return N(a).length;b=(""+b).toLowerCase();d=!0}}function hb(a,b,c){var d=!1;if(void 0===b||0>b)b=0;if(b>this.length)return"";if(void 0===c||c>this.length)c=this.length;if(0>=c)return"";c>>>=0;b>>>=0;if(c<=b)return"";for(a||(a="utf8");;)switch(a){case "hex":a=b;b=c;c=this.length;if(!a||0>a)a=0;if(!b||0>b||b>c)b=c;d="";for(c=a;c<b;++c)a=d,d=this[c],d=16>d?"0"+d.toString(16):d.toString(16),d=a+d;return d;case "utf8":case "utf-8":return za(this,b,c);case "ascii":a="";for(c=Math.min(this.length,
c);b<c;++b)a+=String.fromCharCode(this[b]&127);return a;case "latin1":case "binary":a="";for(c=Math.min(this.length,c);b<c;++b)a+=String.fromCharCode(this[b]);return a;case "base64":return b=0===b&&c===this.length?ta(this):ta(this.slice(b,c)),b;case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":b=this.slice(b,c);c="";for(a=0;a<b.length;a+=2)c+=String.fromCharCode(b[a]+256*b[a+1]);return c;default:if(d)throw new TypeError("Unknown encoding: "+a);a=(a+"").toLowerCase();d=!0}}function y(a,b,c){var d=
a[b];a[b]=a[c];a[c]=d}function Aa(a,b,c,d,e){if(0===a.length)return-1;"string"===typeof c?(d=c,c=0):2147483647<c?c=2147483647:-2147483648>c&&(c=-2147483648);c=+c;isNaN(c)&&(c=e?0:a.length-1);0>c&&(c=a.length+c);if(c>=a.length){if(e)return-1;c=a.length-1}else if(0>c)if(e)c=0;else return-1;"string"===typeof b&&(b=f.from(b,d));if(v(b))return 0===b.length?-1:Ba(a,b,c,d,e);if("number"===typeof b)return b&=255,f.TYPED_ARRAY_SUPPORT&&"function"===typeof Uint8Array.prototype.indexOf?e?Uint8Array.prototype.indexOf.call(a,
b,c):Uint8Array.prototype.lastIndexOf.call(a,b,c):Ba(a,[b],c,d,e);throw new TypeError("val must be string, number or Buffer");}function Ba(a,b,c,d,e){function g(a,b){return 1===h?a[b]:a.readUInt16BE(b*h)}var h=1,f=a.length,p=b.length;if(void 0!==d&&(d=String(d).toLowerCase(),"ucs2"===d||"ucs-2"===d||"utf16le"===d||"utf-16le"===d)){if(2>a.length||2>b.length)return-1;h=2;f/=2;p/=2;c/=2}if(e)for(d=-1;c<f;c++)if(g(a,c)===g(b,-1===d?0:c-d)){if(-1===d&&(d=c),c-d+1===p)return d*h}else-1!==d&&(c-=c-d),d=
-1;else for(c+p>f&&(c=f-p);0<=c;c--){f=!0;for(d=0;d<p;d++)if(g(a,c+d)!==g(b,d)){f=!1;break}if(f)return c}return-1}function za(a,b,c){c=Math.min(a.length,c);for(var d=[];b<c;){var e=a[b],g=null,h=239<e?4:223<e?3:191<e?2:1;if(b+h<=c)switch(h){case 1:128>e&&(g=e);break;case 2:var f=a[b+1];128===(f&192)&&(e=(e&31)<<6|f&63,127<e&&(g=e));break;case 3:f=a[b+1];var p=a[b+2];128===(f&192)&&128===(p&192)&&(e=(e&15)<<12|(f&63)<<6|p&63,2047<e&&(55296>e||57343<e)&&(g=e));break;case 4:f=a[b+1];p=a[b+2];var k=a[b+
3];128===(f&192)&&128===(p&192)&&128===(k&192)&&(e=(e&15)<<18|(f&63)<<12|(p&63)<<6|k&63,65535<e&&1114112>e&&(g=e))}null===g?(g=65533,h=1):65535<g&&(g-=65536,d.push(g>>>10&1023|55296),g=56320|g&1023);d.push(g);b+=h}a=d.length;if(a<=Ca)d=String.fromCharCode.apply(String,d);else{c="";for(b=0;b<a;)c+=String.fromCharCode.apply(String,d.slice(b,b+=Ca));d=c}return d}function n(a,b,c){if(0!==a%1||0>a)throw new RangeError("offset is not uint");if(a+b>c)throw new RangeError("Trying to access beyond buffer length");
}function q(a,b,c,d,e,g){if(!v(a))throw new TypeError('"buffer" argument must be a Buffer instance');if(b>e||b<g)throw new RangeError('"value" argument is out of bounds');if(c+d>a.length)throw new RangeError("Index out of range");}function O(a,b,c,d){0>b&&(b=65535+b+1);for(var e=0,g=Math.min(a.length-c,2);e<g;++e)a[c+e]=(b&255<<8*(d?e:1-e))>>>8*(d?e:1-e)}function P(a,b,c,d){0>b&&(b=4294967295+b+1);for(var e=0,g=Math.min(a.length-c,4);e<g;++e)a[c+e]=b>>>8*(d?e:3-e)&255}function Q(a,b,c,d,e,g){if(c+
d>a.length)throw new RangeError("Index out of range");if(0>c)throw new RangeError("Index out of range");}function N(a,b){b=b||Infinity;for(var c,d=a.length,e=null,g=[],h=0;h<d;++h){c=a.charCodeAt(h);if(55295<c&&57344>c){if(!e){if(56319<c){-1<(b-=3)&&g.push(239,191,189);continue}else if(h+1===d){-1<(b-=3)&&g.push(239,191,189);continue}e=c;continue}if(56320>c){-1<(b-=3)&&g.push(239,191,189);e=c;continue}c=(e-55296<<10|c-56320)+65536}else e&&-1<(b-=3)&&g.push(239,191,189);e=null;if(128>c){if(0>--b)break;
g.push(c)}else if(2048>c){if(0>(b-=2))break;g.push(c>>6|192,c&63|128)}else if(65536>c){if(0>(b-=3))break;g.push(c>>12|224,c>>6&63|128,c&63|128)}else if(1114112>c){if(0>(b-=4))break;g.push(c>>18|240,c>>12&63|128,c>>6&63|128,c&63|128)}else throw Error("Invalid code point");}return g}function Da(a){for(var b=[],c=0;c<a.length;++c)b.push(a.charCodeAt(c)&255);return b}function ya(a){a=(a.trim?a.trim():a.replace(/^\s+|\s+$/g,"")).replace(ib,"");if(2>a.length)a="";else for(;0!==a.length%4;)a+="=";Z||sa();
var b=a.length;if(0<b%4)throw Error("Invalid string. Length must be a multiple of 4");var c="="===a[b-2]?2:"="===a[b-1]?1:0;var d=new jb(3*b/4-c);var e=0<c?b-4:b;var g=0;for(b=0;b<e;b+=4){var h=t[a.charCodeAt(b)]<<18|t[a.charCodeAt(b+1)]<<12|t[a.charCodeAt(b+2)]<<6|t[a.charCodeAt(b+3)];d[g++]=h>>16&255;d[g++]=h>>8&255;d[g++]=h&255}2===c?(h=t[a.charCodeAt(b)]<<2|t[a.charCodeAt(b+1)]>>4,d[g++]=h&255):1===c&&(h=t[a.charCodeAt(b)]<<10|t[a.charCodeAt(b+1)]<<4|t[a.charCodeAt(b+2)]>>2,d[g++]=h>>8&255,d[g++]=
h&255);return d}function F(a,b,c,d){for(var e=0;e<d&&!(e+c>=b.length||e>=a.length);++e)b[e+c]=a[e];return e}function C(a){return null!=a&&(!!a._isBuffer||Ea(a)||"function"===typeof a.readFloatLE&&"function"===typeof a.slice&&Ea(a.slice(0,0)))}function Ea(a){return!!a.constructor&&"function"===typeof a.constructor.isBuffer&&a.constructor.isBuffer(a)}function z(a,b){var c={seen:[],stylize:kb};3<=arguments.length&&(c.depth=arguments[2]);4<=arguments.length&&(c.colors=arguments[3]);if("boolean"===typeof b)c.showHidden=
b;else if(b&&b&&R(b))for(var d=Object.keys(b),e=d.length;e--;)c[d[e]]=b[d[e]];void 0===c.showHidden&&(c.showHidden=!1);void 0===c.depth&&(c.depth=2);void 0===c.colors&&(c.colors=!1);void 0===c.customInspect&&(c.customInspect=!0);c.colors&&(c.stylize=lb);return S(c,a,c.depth)}function lb(a,b){return(b=z.styles[b])?"\u001b["+z.colors[b][0]+"m"+a+"\u001b["+z.colors[b][1]+"m":a}function kb(a,b){return a}function mb(a){var b={};a.forEach(function(a,d){b[a]=!0});return b}function S(a,b,c){if(a.customInspect&&
b&&G(b.inspect)&&b.inspect!==z&&(!b.constructor||b.constructor.prototype!==b)){var d=b.inspect(c,a);"string"!==typeof d&&(d=S(a,d,c));return d}if(d=nb(a,b))return d;var e=Object.keys(b),g=mb(e);a.showHidden&&(e=Object.getOwnPropertyNames(b));if(T(b)&&(0<=e.indexOf("message")||0<=e.indexOf("description")))return da(b);if(0===e.length){if(G(b))return a.stylize("[Function"+(b.name?": "+b.name:"")+"]","special");if(H(b))return a.stylize(RegExp.prototype.toString.call(b),"regexp");if(U(b))return a.stylize(Date.prototype.toString.call(b),
"date");if(T(b))return da(b)}d="";var h=!1,f=["{","}"];Array.isArray(b)&&(h=!0,f=["[","]"]);G(b)&&(d=" [Function"+(b.name?": "+b.name:"")+"]");H(b)&&(d=" "+RegExp.prototype.toString.call(b));U(b)&&(d=" "+Date.prototype.toUTCString.call(b));T(b)&&(d=" "+da(b));if(0===e.length&&(!h||0==b.length))return f[0]+d+f[1];if(0>c)return H(b)?a.stylize(RegExp.prototype.toString.call(b),"regexp"):a.stylize("[Object]","special");a.seen.push(b);e=h?ob(a,b,c,g,e):e.map(function(d){return ea(a,b,c,g,d,h)});a.seen.pop();
return pb(e,d,f)}function nb(a,b){if(void 0===b)return a.stylize("undefined","undefined");if("string"===typeof b)return b="'"+JSON.stringify(b).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'",a.stylize(b,"string");if("number"===typeof b)return a.stylize(""+b,"number");if("boolean"===typeof b)return a.stylize(""+b,"boolean");if(null===b)return a.stylize("null","null")}function da(a){return"["+Error.prototype.toString.call(a)+"]"}function ob(a,b,c,d,e){for(var g=[],h=0,f=b.length;h<
f;++h)Object.prototype.hasOwnProperty.call(b,String(h))?g.push(ea(a,b,c,d,String(h),!0)):g.push("");e.forEach(function(e){e.match(/^\d+$/)||g.push(ea(a,b,c,d,e,!0))});return g}function ea(a,b,c,d,e,g){var h,f;b=Object.getOwnPropertyDescriptor(b,e)||{value:b[e]};b.get?f=b.set?a.stylize("[Getter/Setter]","special"):a.stylize("[Getter]","special"):b.set&&(f=a.stylize("[Setter]","special"));Object.prototype.hasOwnProperty.call(d,e)||(h="["+e+"]");f||(0>a.seen.indexOf(b.value)?(f=null===c?S(a,b.value,
null):S(a,b.value,c-1),-1<f.indexOf("\n")&&(f=g?f.split("\n").map(function(a){return"  "+a}).join("\n").substr(2):"\n"+f.split("\n").map(function(a){return"   "+a}).join("\n"))):f=a.stylize("[Circular]","special"));if(void 0===h){if(g&&e.match(/^\d+$/))return f;h=JSON.stringify(""+e);h.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(h=h.substr(1,h.length-2),h=a.stylize(h,"name")):(h=h.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),h=a.stylize(h,"string"))}return h+": "+f}function pb(a,b,c){return 60<
a.reduce(function(a,b){b.indexOf("\n");return a+b.replace(/\u001b\[\d\d?m/g,"").length+1},0)?c[0]+(""===b?"":b+"\n ")+" "+a.join(",\n  ")+" "+c[1]:c[0]+b+" "+a.join(", ")+" "+c[1]}function H(a){return R(a)&&"[object RegExp]"===Object.prototype.toString.call(a)}function R(a){return"object"===typeof a&&null!==a}function U(a){return R(a)&&"[object Date]"===Object.prototype.toString.call(a)}function T(a){return R(a)&&("[object Error]"===Object.prototype.toString.call(a)||a instanceof Error)}function G(a){return"function"===
typeof a}function Fa(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a}function Ga(a,b){if(a===b)return 0;for(var c=a.length,d=b.length,e=0,g=Math.min(c,d);e<g;++e)if(a[e]!==b[e]){c=a[e];d=b[e];break}return c<d?-1:d<c?1:0}function Ha(){return"undefined"!==typeof fa?fa:fa=function(){return"foo"===function(){}.name}()}function Ia(a){return C(a)||"function"!==typeof ha.ArrayBuffer?!1:"function"===typeof ArrayBuffer.isView?
ArrayBuffer.isView(a):a?a instanceof DataView||a.buffer&&a.buffer instanceof ArrayBuffer?!0:!1:!1}function k(a,b){a||r(a,!0,b,"==",ia)}function Ja(a){if(G(a))return Ha()?a.name:(a=a.toString().match(qb))&&a[1]}function ja(a){this.name="AssertionError";this.actual=a.actual;this.expected=a.expected;this.operator=a.operator;a.message?(this.message=a.message,this.generatedMessage=!1):(this.message=Ka(La(this.actual),128)+" "+this.operator+" "+Ka(La(this.expected),128),this.generatedMessage=!0);var b=
a.stackStartFunction||r;Error.captureStackTrace?Error.captureStackTrace(this,b):(a=Error(),a.stack&&(a=a.stack,b=Ja(b),b=a.indexOf("\n"+b),0<=b&&(b=a.indexOf("\n",b+1),a=a.substring(b+1)),this.stack=a))}function Ka(a,b){return"string"===typeof a?a.length<b?a:a.slice(0,b):a}function La(a){if(Ha()||!G(a))return z(a);a=Ja(a);return"[Function"+(a?": "+a:"")+"]"}function r(a,b,c,d,e){throw new ja({message:c,actual:a,expected:b,operator:d,stackStartFunction:e});}function ia(a,b){a||r(a,!0,b,"==",ia)}function Ma(a,
b,c){a!=b&&r(a,b,c,"==",Ma)}function Na(a,b,c){a==b&&r(a,b,c,"!=",Na)}function Oa(a,b,c){D(a,b,!1)||r(a,b,c,"deepEqual",Oa)}function Pa(a,b,c){D(a,b,!0)||r(a,b,c,"deepStrictEqual",Pa)}function D(a,b,c,d){if(a===b)return!0;if(C(a)&&C(b))return 0===Ga(a,b);if(U(a)&&U(b))return a.getTime()===b.getTime();if(H(a)&&H(b))return a.source===b.source&&a.global===b.global&&a.multiline===b.multiline&&a.lastIndex===b.lastIndex&&a.ignoreCase===b.ignoreCase;if(null!==a&&"object"===typeof a||null!==b&&"object"===
typeof b){if(!Ia(a)||!Ia(b)||Object.prototype.toString.call(a)!==Object.prototype.toString.call(b)||a instanceof Float32Array||a instanceof Float64Array){if(C(a)!==C(b))return!1;d=d||{actual:[],expected:[]};var e=d.actual.indexOf(a);if(-1!==e&&e===d.expected.indexOf(b))return!0;d.actual.push(a);d.expected.push(b);return rb(a,b,c,d)}return 0===Ga(new Uint8Array(a.buffer),new Uint8Array(b.buffer))}return c?a===b:a==b}function Qa(a){return"[object Arguments]"==Object.prototype.toString.call(a)}function rb(a,
b,c,d){if(null===a||void 0===a||null===b||void 0===b)return!1;if(Fa(a)||Fa(b))return a===b;if(c&&Object.getPrototypeOf(a)!==Object.getPrototypeOf(b))return!1;var e=Qa(a),g=Qa(b);if(e&&!g||!e&&g)return!1;if(e)return a=Ra.call(a),b=Ra.call(b),D(a,b,c);e=Sa(a);var f=Sa(b);if(e.length!==f.length)return!1;e.sort();f.sort();for(g=e.length-1;0<=g;g--)if(e[g]!==f[g])return!1;for(g=e.length-1;0<=g;g--)if(f=e[g],!D(a[f],b[f],c,d))return!1;return!0}function Ta(a,b,c){D(a,b,!1)&&r(a,b,c,"notDeepEqual",Ta)}function Ua(a,
b,c){D(a,b,!0)&&r(a,b,c,"notDeepStrictEqual",Ua)}function Va(a,b,c){a!==b&&r(a,b,c,"===",Va)}function Wa(a,b,c){a===b&&r(a,b,c,"!==",Wa)}function Xa(a,b){if(!a||!b)return!1;if("[object RegExp]"==Object.prototype.toString.call(b))return b.test(a);try{if(a instanceof b)return!0}catch(c){}return Error.isPrototypeOf(b)?!1:!0===b.call({},a)}function Ya(a,b,c,d){if("function"!==typeof b)throw new TypeError('"block" argument must be a function');"string"===typeof c&&(d=c,c=null);try{b()}catch(l){var e=l}b=
e;d=(c&&c.name?" ("+c.name+").":".")+(d?" "+d:".");a&&!b&&r(b,c,"Missing expected exception"+d);e="string"===typeof d;var g=!a&&T(b),f=!a&&b&&!c;(g&&e&&Xa(b,c)||f)&&r(b,c,"Got unwanted exception"+d);if(a&&b&&c&&!Xa(b,c)||!a&&b)throw b;}function ka(a,b,c){if(!a)throw{message:c(),scope:b};}function sb(a,b,c){a=Math.max(0,Math.min(360,a));b=Math.max(0,Math.min(1,b));c=Math.max(0,Math.min(1,c));a/=60;b*=c;let d=b*(1-Za(a%2-1)),e=c-b,g;g=1>=a?[b,d,0]:2>=a?[d,b,0]:3>=a?[0,b,d]:4>=a?[0,d,b]:5>=a?[d,0,b]:
6>=a?[b,0,d]:[0,0,0];g.forEach((a,b)=>g[b]=a+e);return g}let oa=Symbol("Comlink.proxy"),db=Symbol("Comlink.endpoint"),cb=Symbol("Comlink.releaseProxy"),W=new WeakSet,ra=new Map([["proxy",{canHandle:a=>a&&a[oa],serialize(a){const {port1:b,port2:c}=new MessageChannel;V(a,b);return[c,[c]]},deserialize:a=>{a.start();return Y(a,[],void 0)}}],["throw",{canHandle:a=>W.has(a),serialize(a){const b=a instanceof Error;let c=a;b&&(c={isError:b,message:a.message,stack:a.stack});return[c,[]]},deserialize(a){if(a.isError)throw Object.assign(Error(),
a);throw a;}}]]),qa=new WeakMap;var ha="undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{},u=[],t=[],jb="undefined"!==typeof Uint8Array?Uint8Array:Array,Z=!1,tb={}.toString,xa=Array.isArray||function(a){return"[object Array]"==tb.call(a)};f.TYPED_ARRAY_SUPPORT=void 0!==ha.TYPED_ARRAY_SUPPORT?ha.TYPED_ARRAY_SUPPORT:!0;f.poolSize=8192;f._augment=function(a){a.__proto__=f.prototype;return a};f.from=function(a,b,c){return ua(null,a,b,c)};f.TYPED_ARRAY_SUPPORT&&
(f.prototype.__proto__=Uint8Array.prototype,f.__proto__=Uint8Array);f.alloc=function(a,b,c){wa(a);a=0>=a?w(null,a):void 0!==b?"string"===typeof c?w(null,a).fill(b,c):w(null,a).fill(b):w(null,a);return a};f.allocUnsafe=function(a){return aa(null,a)};f.allocUnsafeSlow=function(a){return aa(null,a)};f.isBuffer=C;f.compare=function(a,b){if(!v(a)||!v(b))throw new TypeError("Arguments must be Buffers");if(a===b)return 0;for(var c=a.length,d=b.length,e=0,g=Math.min(c,d);e<g;++e)if(a[e]!==b[e]){c=a[e];d=
b[e];break}return c<d?-1:d<c?1:0};f.isEncoding=function(a){switch(String(a).toLowerCase()){case "hex":case "utf8":case "utf-8":case "ascii":case "latin1":case "binary":case "base64":case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":return!0;default:return!1}};f.concat=function(a,b){if(!xa(a))throw new TypeError('"list" argument must be an Array of Buffers');if(0===a.length)return f.alloc(0);var c;if(void 0===b)for(c=b=0;c<a.length;++c)b+=a[c].length;b=f.allocUnsafe(b);var d=0;for(c=0;c<a.length;++c){var e=
a[c];if(!v(e))throw new TypeError('"list" argument must be an Array of Buffers');e.copy(b,d);d+=e.length}return b};f.byteLength=va;f.prototype._isBuffer=!0;f.prototype.swap16=function(){var a=this.length;if(0!==a%2)throw new RangeError("Buffer size must be a multiple of 16-bits");for(var b=0;b<a;b+=2)y(this,b,b+1);return this};f.prototype.swap32=function(){var a=this.length;if(0!==a%4)throw new RangeError("Buffer size must be a multiple of 32-bits");for(var b=0;b<a;b+=4)y(this,b,b+3),y(this,b+1,b+
2);return this};f.prototype.swap64=function(){var a=this.length;if(0!==a%8)throw new RangeError("Buffer size must be a multiple of 64-bits");for(var b=0;b<a;b+=8)y(this,b,b+7),y(this,b+1,b+6),y(this,b+2,b+5),y(this,b+3,b+4);return this};f.prototype.toString=function(){var a=this.length|0;return 0===a?"":0===arguments.length?za(this,0,a):hb.apply(this,arguments)};f.prototype.equals=function(a){if(!v(a))throw new TypeError("Argument must be a Buffer");return this===a?!0:0===f.compare(this,a)};f.prototype.inspect=
function(){var a="";0<this.length&&(a=this.toString("hex",0,50).match(/.{2}/g).join(" "),50<this.length&&(a+=" ... "));return"<Buffer "+a+">"};f.prototype.compare=function(a,b,c,d,e){if(!v(a))throw new TypeError("Argument must be a Buffer");void 0===b&&(b=0);void 0===c&&(c=a?a.length:0);void 0===d&&(d=0);void 0===e&&(e=this.length);if(0>b||c>a.length||0>d||e>this.length)throw new RangeError("out of range index");if(d>=e&&b>=c)return 0;if(d>=e)return-1;if(b>=c)return 1;b>>>=0;c>>>=0;d>>>=0;e>>>=0;
if(this===a)return 0;var g=e-d,f=c-b,l=Math.min(g,f);d=this.slice(d,e);a=a.slice(b,c);for(b=0;b<l;++b)if(d[b]!==a[b]){g=d[b];f=a[b];break}return g<f?-1:f<g?1:0};f.prototype.includes=function(a,b,c){return-1!==this.indexOf(a,b,c)};f.prototype.indexOf=function(a,b,c){return Aa(this,a,b,c,!0)};f.prototype.lastIndexOf=function(a,b,c){return Aa(this,a,b,c,!1)};f.prototype.write=function(a,b,c,d){if(void 0===b)d="utf8",c=this.length,b=0;else if(void 0===c&&"string"===typeof b)d=b,c=this.length,b=0;else if(isFinite(b))b|=
0,isFinite(c)?(c|=0,void 0===d&&(d="utf8")):(d=c,c=void 0);else throw Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");var e=this.length-b;if(void 0===c||c>e)c=e;if(0<a.length&&(0>c||0>b)||b>this.length)throw new RangeError("Attempt to write outside buffer bounds");d||(d="utf8");for(e=!1;;)switch(d){case "hex":a:{b=Number(b)||0;d=this.length-b;c?(c=Number(c),c>d&&(c=d)):c=d;d=a.length;if(0!==d%2)throw new TypeError("Invalid hex string");c>d/2&&(c=d/2);for(d=0;d<c;++d){e=
parseInt(a.substr(2*d,2),16);if(isNaN(e)){a=d;break a}this[b+d]=e}a=d}return a;case "utf8":case "utf-8":return F(N(a,this.length-b),this,b,c);case "ascii":return F(Da(a),this,b,c);case "latin1":case "binary":return F(Da(a),this,b,c);case "base64":return F(ya(a),this,b,c);case "ucs2":case "ucs-2":case "utf16le":case "utf-16le":d=a;e=this.length-b;for(var g=[],f=0;f<d.length&&!(0>(e-=2));++f){var l=d.charCodeAt(f);a=l>>8;l%=256;g.push(l);g.push(a)}return F(g,this,b,c);default:if(e)throw new TypeError("Unknown encoding: "+
d);d=(""+d).toLowerCase();e=!0}};f.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};var Ca=4096;f.prototype.slice=function(a,b){var c=this.length;a=~~a;b=void 0===b?c:~~b;0>a?(a+=c,0>a&&(a=0)):a>c&&(a=c);0>b?(b+=c,0>b&&(b=0)):b>c&&(b=c);b<a&&(b=a);if(f.TYPED_ARRAY_SUPPORT)b=this.subarray(a,b),b.__proto__=f.prototype;else{c=b-a;b=new f(c,void 0);for(var d=0;d<c;++d)b[d]=this[d+a]}return b};f.prototype.readUIntLE=function(a,b,c){a|=0;b|=0;c||n(a,
b,this.length);c=this[a];for(var d=1,e=0;++e<b&&(d*=256);)c+=this[a+e]*d;return c};f.prototype.readUIntBE=function(a,b,c){a|=0;b|=0;c||n(a,b,this.length);c=this[a+--b];for(var d=1;0<b&&(d*=256);)c+=this[a+--b]*d;return c};f.prototype.readUInt8=function(a,b){b||n(a,1,this.length);return this[a]};f.prototype.readUInt16LE=function(a,b){b||n(a,2,this.length);return this[a]|this[a+1]<<8};f.prototype.readUInt16BE=function(a,b){b||n(a,2,this.length);return this[a]<<8|this[a+1]};f.prototype.readUInt32LE=
function(a,b){b||n(a,4,this.length);return(this[a]|this[a+1]<<8|this[a+2]<<16)+16777216*this[a+3]};f.prototype.readUInt32BE=function(a,b){b||n(a,4,this.length);return 16777216*this[a]+(this[a+1]<<16|this[a+2]<<8|this[a+3])};f.prototype.readIntLE=function(a,b,c){a|=0;b|=0;c||n(a,b,this.length);c=this[a];for(var d=1,e=0;++e<b&&(d*=256);)c+=this[a+e]*d;c>=128*d&&(c-=Math.pow(2,8*b));return c};f.prototype.readIntBE=function(a,b,c){a|=0;b|=0;c||n(a,b,this.length);c=b;for(var d=1,e=this[a+--c];0<c&&(d*=
256);)e+=this[a+--c]*d;e>=128*d&&(e-=Math.pow(2,8*b));return e};f.prototype.readInt8=function(a,b){b||n(a,1,this.length);return this[a]&128?-1*(255-this[a]+1):this[a]};f.prototype.readInt16LE=function(a,b){b||n(a,2,this.length);a=this[a]|this[a+1]<<8;return a&32768?a|4294901760:a};f.prototype.readInt16BE=function(a,b){b||n(a,2,this.length);a=this[a+1]|this[a]<<8;return a&32768?a|4294901760:a};f.prototype.readInt32LE=function(a,b){b||n(a,4,this.length);return this[a]|this[a+1]<<8|this[a+2]<<16|this[a+
3]<<24};f.prototype.readInt32BE=function(a,b){b||n(a,4,this.length);return this[a]<<24|this[a+1]<<16|this[a+2]<<8|this[a+3]};f.prototype.readFloatLE=function(a,b){b||n(a,4,this.length);return L(this,a,!0,23,4)};f.prototype.readFloatBE=function(a,b){b||n(a,4,this.length);return L(this,a,!1,23,4)};f.prototype.readDoubleLE=function(a,b){b||n(a,8,this.length);return L(this,a,!0,52,8)};f.prototype.readDoubleBE=function(a,b){b||n(a,8,this.length);return L(this,a,!1,52,8)};f.prototype.writeUIntLE=function(a,
b,c,d){a=+a;b|=0;c|=0;d||q(this,a,b,c,Math.pow(2,8*c)-1,0);d=1;var e=0;for(this[b]=a&255;++e<c&&(d*=256);)this[b+e]=a/d&255;return b+c};f.prototype.writeUIntBE=function(a,b,c,d){a=+a;b|=0;c|=0;d||q(this,a,b,c,Math.pow(2,8*c)-1,0);d=c-1;var e=1;for(this[b+d]=a&255;0<=--d&&(e*=256);)this[b+d]=a/e&255;return b+c};f.prototype.writeUInt8=function(a,b,c){a=+a;b|=0;c||q(this,a,b,1,255,0);f.TYPED_ARRAY_SUPPORT||(a=Math.floor(a));this[b]=a&255;return b+1};f.prototype.writeUInt16LE=function(a,b,c){a=+a;b|=
0;c||q(this,a,b,2,65535,0);f.TYPED_ARRAY_SUPPORT?(this[b]=a&255,this[b+1]=a>>>8):O(this,a,b,!0);return b+2};f.prototype.writeUInt16BE=function(a,b,c){a=+a;b|=0;c||q(this,a,b,2,65535,0);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>8,this[b+1]=a&255):O(this,a,b,!1);return b+2};f.prototype.writeUInt32LE=function(a,b,c){a=+a;b|=0;c||q(this,a,b,4,4294967295,0);f.TYPED_ARRAY_SUPPORT?(this[b+3]=a>>>24,this[b+2]=a>>>16,this[b+1]=a>>>8,this[b]=a&255):P(this,a,b,!0);return b+4};f.prototype.writeUInt32BE=function(a,b,
c){a=+a;b|=0;c||q(this,a,b,4,4294967295,0);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>24,this[b+1]=a>>>16,this[b+2]=a>>>8,this[b+3]=a&255):P(this,a,b,!1);return b+4};f.prototype.writeIntLE=function(a,b,c,d){a=+a;b|=0;d||(d=Math.pow(2,8*c-1),q(this,a,b,c,d-1,-d));d=0;var e=1,f=0;for(this[b]=a&255;++d<c&&(e*=256);)0>a&&0===f&&0!==this[b+d-1]&&(f=1),this[b+d]=(a/e>>0)-f&255;return b+c};f.prototype.writeIntBE=function(a,b,c,d){a=+a;b|=0;d||(d=Math.pow(2,8*c-1),q(this,a,b,c,d-1,-d));d=c-1;var e=1,f=0;for(this[b+
d]=a&255;0<=--d&&(e*=256);)0>a&&0===f&&0!==this[b+d+1]&&(f=1),this[b+d]=(a/e>>0)-f&255;return b+c};f.prototype.writeInt8=function(a,b,c){a=+a;b|=0;c||q(this,a,b,1,127,-128);f.TYPED_ARRAY_SUPPORT||(a=Math.floor(a));0>a&&(a=255+a+1);this[b]=a&255;return b+1};f.prototype.writeInt16LE=function(a,b,c){a=+a;b|=0;c||q(this,a,b,2,32767,-32768);f.TYPED_ARRAY_SUPPORT?(this[b]=a&255,this[b+1]=a>>>8):O(this,a,b,!0);return b+2};f.prototype.writeInt16BE=function(a,b,c){a=+a;b|=0;c||q(this,a,b,2,32767,-32768);f.TYPED_ARRAY_SUPPORT?
(this[b]=a>>>8,this[b+1]=a&255):O(this,a,b,!1);return b+2};f.prototype.writeInt32LE=function(a,b,c){a=+a;b|=0;c||q(this,a,b,4,2147483647,-2147483648);f.TYPED_ARRAY_SUPPORT?(this[b]=a&255,this[b+1]=a>>>8,this[b+2]=a>>>16,this[b+3]=a>>>24):P(this,a,b,!0);return b+4};f.prototype.writeInt32BE=function(a,b,c){a=+a;b|=0;c||q(this,a,b,4,2147483647,-2147483648);0>a&&(a=4294967295+a+1);f.TYPED_ARRAY_SUPPORT?(this[b]=a>>>24,this[b+1]=a>>>16,this[b+2]=a>>>8,this[b+3]=a&255):P(this,a,b,!1);return b+4};f.prototype.writeFloatLE=
function(a,b,c){c||Q(this,a,b,4);M(this,a,b,!0,23,4);return b+4};f.prototype.writeFloatBE=function(a,b,c){c||Q(this,a,b,4);M(this,a,b,!1,23,4);return b+4};f.prototype.writeDoubleLE=function(a,b,c){c||Q(this,a,b,8);M(this,a,b,!0,52,8);return b+8};f.prototype.writeDoubleBE=function(a,b,c){c||Q(this,a,b,8);M(this,a,b,!1,52,8);return b+8};f.prototype.copy=function(a,b,c,d){c||(c=0);d||0===d||(d=this.length);b>=a.length&&(b=a.length);b||(b=0);0<d&&d<c&&(d=c);if(d===c||0===a.length||0===this.length)return 0;
if(0>b)throw new RangeError("targetStart out of bounds");if(0>c||c>=this.length)throw new RangeError("sourceStart out of bounds");if(0>d)throw new RangeError("sourceEnd out of bounds");d>this.length&&(d=this.length);a.length-b<d-c&&(d=a.length-b+c);var e=d-c;if(this===a&&c<b&&b<d)for(d=e-1;0<=d;--d)a[d+b]=this[d+c];else if(1E3>e||!f.TYPED_ARRAY_SUPPORT)for(d=0;d<e;++d)a[d+b]=this[d+c];else Uint8Array.prototype.set.call(a,this.subarray(c,c+e),b);return e};f.prototype.fill=function(a,b,c,d){if("string"===
typeof a){"string"===typeof b?(d=b,b=0,c=this.length):"string"===typeof c&&(d=c,c=this.length);if(1===a.length){var e=a.charCodeAt(0);256>e&&(a=e)}if(void 0!==d&&"string"!==typeof d)throw new TypeError("encoding must be a string");if("string"===typeof d&&!f.isEncoding(d))throw new TypeError("Unknown encoding: "+d);}else"number"===typeof a&&(a&=255);if(0>b||this.length<b||this.length<c)throw new RangeError("Out of range index");if(c<=b)return this;b>>>=0;c=void 0===c?this.length:c>>>0;a||(a=0);if("number"===
typeof a)for(d=b;d<c;++d)this[d]=a;else for(a=v(a)?a:N((new f(a,d)).toString()),e=a.length,d=0;d<c-b;++d)this[d+b]=a[d%e];return this};var ib=/[^+\/0-9A-Za-z-_]/g,ub="function"===typeof Object.create?function(a,b){a.super_=b;a.prototype=Object.create(b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}})}:function(a,b){a.super_=b;var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};z.colors={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,
27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]};z.styles={special:"cyan",number:"yellow","boolean":"yellow",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"};var vb=Object.prototype.hasOwnProperty,Sa=Object.keys||function(a){var b=[],c;for(c in a)vb.call(a,c)&&b.push(c);return b},Ra=Array.prototype.slice,fa,qb=/\s*function\s+([^\(\s]*)\s*/;k.AssertionError=ja;ub(ja,Error);k.fail=r;k.ok=ia;k.equal=
Ma;k.notEqual=Na;k.deepEqual=Oa;k.deepStrictEqual=Pa;k.notDeepEqual=Ta;k.notDeepStrictEqual=Ua;k.strictEqual=Va;k.notStrictEqual=Wa;k.throws=function(a,b,c){Ya(!0,a,b,c)};k.doesNotThrow=function(a,b,c){Ya(!1,a,b,c)};k.ifError=function(a){if(a)throw a;};let wb=Math.pow(2,32)-1;class E{constructor(a){this.fns=a;this.sample=function*(a,c,d){let {fns:b,d:f}=this,[h,...l]=b;if(0==b.length)return[];for(let b of h.sample(a,c,d))this.x.set(b),l.length?E.apply(l,this.x,this.y):this.y.set(b),yield this.y.subarray(0,
f)};this.fn=(a,c=new Float32Array(this.d))=>{let {fns:b,domain:e,d:f}=this;k.equal(a.length,e);k.equal(c.length,f);this.x.set(a);E.apply(b,this.x,this.y);c.set(this.y.subarray(0,f));return c};k(a.length,"fns cannot be empty");a=Math.max(this.domainMax,this.dMax);this.x=new Float32Array(a);this.y=new Float32Array(a)}get first(){return this.fns[0]}get last(){return this.fns[this.fns.length-1]}get domain(){return this.first.domain}get d(){return this.last.d}get domainMax(){return this.fns.reduce((a,
b)=>Math.max(b.domain,a),0)}get dMax(){return this.fns.reduce((a,b)=>Math.max(b.d,a),0)}}E.apply=(a,b,c)=>{k.equal(b.length,c.length);for(let d of a){d.fn(b.subarray(0,d.domain),c.subarray(0,d.d));for(a=0;a<c.length;a++)isFinite(c[a])||(c[a]=Math.sign(c[a])*wb),isNaN(c[a])&&(c[a]=0);b.set(c)}};E.Builder=class{constructor(){this.fns=[];this.add=a=>{let {fns:b,last:c}=this;if(c&&a.domain!==c.d)throw Error(`Cannot add ${a} to composite, because its domain is not ${c.d}`);b.push(a);return this};this.build=
()=>new E(this.fns)}get d(){return this.last.d}get last(){return this.fns[this.fns.length-1]}};class la{constructor(a,b,c){this.d=a;this.a=b;this.b=c;this.fn=(a,b=new Float32Array(this.d))=>{let {a:c,b:d,d:e}=this;k.equal(a.length,e);k.equal(b.length,e);for(let f=0;f<e;f++)b[f]=c[f]+a[f]*(d[f]-c[f]);return b};this.sample=function*(a,b,c){function*d(b){for(let c=0;c<a;c++)yield[...b,c/a]}let {d:e,fn:f}=this;a=la.nPerLevel(e,a);let g=[[]],k=0;for(;g.length&&k<c;){let a=g.pop();a.length<e?g.push(...d(a)):
k++>=b&&(yield f(a))}};k.equal(b.length,a);k.equal(c.length,a);this.domain=a}}la.nPerLevel=(a,b)=>Math.round(Math.pow(b,1/a));class A{constructor(a,b){this.d=a;this.l=b;this.fn=(a,b)=>this.interval.fn(a,b);this.sample=(a,b,e)=>this.interval.sample(a,b,e);this.interval=new la(a,Array(a).fill(-b/2),Array(a).fill(b/2))}get domain(){return this.d}}class I{constructor(a,b){this.d=a;this.r=b;this.sample=function*(a,b,e){let c=new A(this.domain,2*Math.PI);for(let d of c.sample(a,b,e))yield this.fn(d)};this.fn=
(a,b=new Float32Array(this.d))=>{let {d:c,r:d}=this;k.equal(a.length,c-1);k.equal(b.length,c);b[0]=d;for(let c=1;c<b.length;c++){let d=Math.cos(a[c-1]);b[c]=b[0]*Math.sin(a[c-1]);b[0]*=d}return b}}get domain(){return this.d-1}}class xb{constructor(a,b,c){this.d=a;this.r=b;this.t=c;this.sample=function*(a,b,c){let d=new A(this.domain,2*Math.PI);for(let e of d.sample(a,b,c))yield this.fn(e)};this.fn=(a,b=new Float32Array(this.d))=>{let {domain:c,d,sphere:e,circle:f}=this;k.equal(a.length,c);k.equal(b.length,
d);e.fn(a,b);a=f.fn(a.subarray(d-2));b[0]+=a[0];b[d-1]+=a[1];return b};this.sphere=new I(a,c);this.circle=new I(2,b)}get domain(){return this.d-1}}class $a{constructor(a,b,c,d,e=Math.cos,f=Math.sin){this.d=a;this.theta=b;this.d0=c;this.d1=d;this.f0=e;this.f1=f;this.sample=function*(a,b,c){let d=new A(this.domain,2);for(let e of d.sample(a,b,c))yield this.fn(e)};this.fn=(a,b=new Float32Array(this.d))=>{let {d:c,d0:d,d1:e,r0:f,r1:g}=this;k.equal(a.length,c);k.equal(b.length,c);b.set(a);let h=a[d];a=
a[e];b[d]=h*f-a*g;b[e]=h*g+a*f;return b};this.r0=e(b);this.r1=f(b)}get domain(){return this.d}}class yb{constructor(a,b,c){this.d=a;this.a=b;this.k=c;this.sample=function*(a,b,c){let d=new A(this.domain,4*Math.PI);for(let e of d.sample(a,b,c))yield this.fn(e)};this.fn=(a,b=new Float32Array(this.d))=>{let {a:c,k:d,domain:e,d:f}=this;k.equal(a.length,f-1);k.equal(b.length,f);this.sphere.fn(a,b);var m=0;for(let b=0;b<e;b++)m+=d[b]*a[b];a=Math.exp(m);for(m=0;m<f;m++)b[m]=b[m]*c[m]*a;return b};this.sphere=
new I(a,1)}get domain(){return this.d-1}}class J{constructor(a,b){this.from=a;this.to=b;this.sample=function*(a,b,e){let c=new A(this.domain,2);for(let d of c.sample(a,b,e))yield this.fn(d)};this.fn=(a,b=new Float32Array(this.to))=>{let {from:c,to:d,fromTemp:f,toTemp:l}=this;k.equal(a.length,c);k.equal(b.length,d);if(c===d)return b.set(a),b;for(f.set(a);c<d;)J.up(f.subarray(0,c),l.subarray(0,++c)),f.set(l);for(;c>d;)J.down(f.subarray(0,c),l.subarray(0,--c)),f.set(l);b.set(l.subarray(0,d));return b};
this.fromTemp=new Float32Array(Math.max(a,b));this.toTemp=new Float32Array(Math.max(a,b))}get domain(){return this.from}get d(){return this.to}}J.up=(a,b)=>{k.equal(b.length,a.length+1);var c,d=0;for(c=0;c<a.length;c++)d+=a[c]*a[c];c=d;d=c+1;b[0]=(c-1)/d;for(c=1;c<=a.length;c++)b[c]=2*a[c-1]/d};J.down=(a,b)=>{k.equal(b.length,a.length-1);for(let c=0;c<b.length;c++)b[c]=a[c+1]/(1-a[0])};class zb{constructor(a,b,c){this.d=a;this.r=b;this.t=c;this.sample=function*(a,b,c){let d=new A(this.domain,2*Math.PI);
for(let e of d.sample(a,b,c))yield this.fn(e)};this.fn=(a,b=new Float32Array(this.d))=>{let {cross:c,d,r:e}=this;k.equal(a.length,d-1,`torus expects an input of ${d-1}; got ${a.length}`);let f=new $a(d,a[d-2],0,d-1);c.fn(a.subarray(0,d-2),b.subarray(0,d-1));b[0]+=e;f.fn(b,b);return b};k(2<a,`torus is only defined for d > 2; got ${a}`);this.cross=new I(a-1,c)}get domain(){return this.d-1}}let Ab=(a,b=2)=>JSON.stringify(a,null,b);class Bb{constructor(a){this.scope=a;this.resolvePipe=a=>{let [b,...d]=
a.steps,e=(new E.Builder).add(this.resolveStep(a.d0,b));for(let a=0;a<d.length;a++)e.add(this.resolveStep(e.d,d[a]));return{n:a.n,fn:e.build()}};this.resolveStep=(a,{type:c,args:d})=>{a=Cb[c](a);return Db[c](a,...d.map(a=>this.resolve(a)))};this.resolveFn=({name:a,args:c})=>{let b=Math[a],e=typeof b;this.expect("function"===e,a,"resolve to a function",`was ${e}`);return b(...c.map(a=>this.resolve(a)))};this.resolveAccess=({id:a,index:c})=>{let b=this.scope[a];this.assert(b,()=>`failed to resolve access target ${a}`);
return"id"===c.kind&&c.id in b?b[c.id]:b[this.resolve(c)]};this.resolveId=a=>{let b;if(a in this.scope)b=this.scope[a];else if(a in Math)b=Math[a];else{let c=a.toUpperCase();c in Math&&(b=Math[c])}this.assert(b,()=>`failed to resolve id ${a}`);return b};this.resolveArith=({op:a,operands:c})=>{let [b,e]=c.map(a=>this.resolve(a,"number"));return Eb[a](b,e)};this.isNodeDynamic=a=>{switch(a.kind){case "fn":return a.args.some(this.isNodeDynamic);case "id":return"number"===typeof this.resolve(a);case "arith":return a.operands.some(this.isNodeDynamic);
default:return!1}}}resolve(a,b){let c;switch(a.kind){case "pipe":c=this.resolvePipe(a);break;case "arith":c=this.resolveArith(a);break;case "number":c=a.value;break;case "fn":c=this.resolveFn(a);break;case "access":c=this.resolveAccess(a);break;case "id":c=this.resolveId(a.id);break;case "paren":c=this.resolve(a.scalar)}if(b){let d=typeof c;this.expect(d===b,a,`be a ${b}`,`was ${d}`)}"number"===b&&this.expect(!isNaN(c),a,"be a number","was NaN");return c}assert(a,b){ka(a,this.scope,b)}expect(a,b,
c,d){this.assert(a,()=>`Expected ${Ab(b,0)} to ${c}, but ${d}`)}}let Eb={"+":(a,b)=>a+b,"-":(a,b)=>null==b?-a:a-b,"*":(a,b)=>a*b,"/":(a,b)=>a/b,"**":(a,b)=>Math.pow(a,b),"^":(a,b)=>Math.pow(a,b)},Db={cube:(a,b)=>new A(a,b),sphere:(a,b)=>new I(a,b),spiral:(a,b,c)=>new yb(a,Array(a).fill(b),Array(a-1).fill(c)),torus:(a,b,c)=>new zb(a,b,c),fucked_up_torus:(a,b,c)=>new xb(a,b,c),rotate:(a,b,c,d,e=Math.cos,f=Math.sin)=>{ka(0<=c&&c<a,null,()=>`rotate: Expected 0 <= d0 = ${c} < d = ${a}`);ka(0<=d&&d<a,null,
()=>`rotate: Expected 0 <= d1 = ${d} < d = ${a}`);return new $a(a,b,c,d,e,f)},stereo:(a,b)=>new J(a,b)},Cb={cube:a=>a,sphere:a=>a+1,spiral:a=>a+1,torus:a=>a+1,fucked_up_torus:a=>a+1,rotate:a=>a,r:a=>a,stereo:a=>a},{abs:Za,min:Fb,sign:Gb}=Math;class Hb{constructor(a,b,c,d){this.scope=a;this.hsv=c;this.iterate=()=>{let a=this.computePosition(),b=this.computeColor(a);return{d:this.d,position:a,color:b}};this.computePosition=()=>{let {fn:a,n:b,d:c,offset:d,size:e}=this,f=new Float32Array(c*e),g=0;for(let h of a.sample(b,
d,d+e))f.set(h,c*g++);return f};this.computeColor=a=>{let {d:b,hsv:c,size:d}=this,e=new Float32Array(3*d),{extent:f}=this.scope;for(let h=0;h<d;h++){var g=a.subarray(h*b,(h+1)*b);this.scope.p=g.map((a,b)=>(b=f[b])?Gb(a)*Fb(1,Za(a)/b):0);this.scope.i=h;g=360*this.resolveNumber("h",c.h);let d=this.resolveNumber("s",c.s),k=this.resolveNumber("v",c.v);g=sb(g,d,k);e.set(g,3*h)}return e};this.resolver=new Bb(a);let {n:e,fn:f}=this.resolvePipe(b);a=d.offset;d=d.size;b=a+d;k(0<=a,`offset must be non-negative; got ${a}`);
k(b<=e,`offset + size must be <= n; got ${a} + ${d} = ${b} > ${e}`);this.n=e;this.fn=f;this.offset=a;this.size=b-a}get d(){return this.fn.d}resolvePipe(a){try{return this.resolver.resolve(a)}catch({message:b,scope:c}){throw{context:"pipe",message:b,scope:c};}}resolveNumber(a,b){try{return this.resolver.resolve(b,"number")}catch({message:c,scope:d}){throw{context:a,message:c,scope:d};}}}V({iterate:(a,b)=>(new Hb(a.scope,a.pipe,a.hsv,b)).iterate()});ma.newWorker=()=>new Worker("/stereo/pipe/worker.js");
return ma})({});
//# sourceMappingURL=worker.js.map
